/* Generated by .github/workflows/idl-surface.yml from
 * @webref/idl, the curated WebIDL of the specifications.
 * Do not edit: regenerate by touching fixtures/idl-request.txt.
 */
var SURFACE = {
"AbortController": {
"attributes": [
"signal"
],
"methods": [
"abort"
]
},
"AbortSignal": {
"attributes": [
"aborted",
"onabort",
"reason"
],
"methods": [
"abort",
"throwIfAborted",
"timeout"
]
},
"AbstractRange": {
"attributes": [
"collapsed",
"endContainer",
"endOffset",
"startContainer",
"startOffset"
],
"methods": []
},
"AbstractWorker": {
"attributes": [
"onerror"
],
"methods": []
},
"Animatable": {
"attributes": [],
"methods": [
"animate",
"getAnimations"
]
},
"Animation": {
"attributes": [
"effect",
"finished",
"id",
"oncancel",
"onfinish",
"onremove",
"pending",
"playState",
"playbackRate",
"ready",
"replaceState",
"timeline"
],
"methods": [
"cancel",
"commitStyles",
"finish",
"pause",
"persist",
"play",
"reverse",
"updatePlaybackRate"
]
},
"AnimationEffect": {
"attributes": [],
"methods": [
"getComputedTiming",
"getTiming",
"updateTiming"
]
},
"AnimationFrameProvider": {
"attributes": [],
"methods": [
"cancelAnimationFrame",
"requestAnimationFrame"
]
},
"Attr": {
"attributes": [
"localName",
"name",
"namespaceURI",
"ownerElement",
"prefix",
"specified",
"value"
],
"methods": []
},
"AudioTrack": {
"attributes": [
"enabled",
"id",
"kind",
"label",
"language"
],
"methods": []
},
"AudioTrackList": {
"attributes": [
"length",
"onaddtrack",
"onchange",
"onremovetrack"
],
"methods": [
"getTrackById"
]
},
"BarProp": {
"attributes": [
"visible"
],
"methods": []
},
"BatteryManager": {
"attributes": [
"charging",
"chargingTime",
"dischargingTime",
"level",
"onchargingchange",
"onchargingtimechange",
"ondischargingtimechange",
"onlevelchange"
],
"methods": []
},
"BeforeUnloadEvent": {
"attributes": [
"returnValue"
],
"methods": []
},
"Blob": {
"attributes": [
"size",
"type"
],
"methods": [
"arrayBuffer",
"bytes",
"slice",
"stream",
"text",
"textStream"
]
},
"Body": {
"attributes": [
"body",
"bodyUsed"
],
"methods": [
"arrayBuffer",
"blob",
"bytes",
"formData",
"json",
"text",
"textStream"
]
},
"BroadcastChannel": {
"attributes": [
"name",
"onmessage",
"onmessageerror"
],
"methods": [
"close",
"postMessage"
]
},
"ByteLengthQueuingStrategy": {
"attributes": [
"highWaterMark",
"size"
],
"methods": []
},
"CSS": {
"attributes": [
"highlights"
],
"methods": [
"cap",
"ch",
"cm",
"cqb",
"cqh",
"cqi",
"cqmax",
"cqmin",
"cqw",
"deg",
"dpcm",
"dpi",
"dppx",
"dvb",
"dvh",
"dvi",
"dvmax",
"dvmin",
"dvw",
"em",
"escape",
"ex",
"fr",
"grad",
"ic",
"in",
"kHz",
"lh",
"lvb",
"lvh",
"lvi",
"lvmax",
"lvmin",
"lvw",
"mm",
"ms",
"number",
"pc",
"percent",
"pt",
"px",
"rad",
"rcap",
"rch",
"rem",
"rex",
"ric",
"rlh",
"s",
"svb",
"svh",
"svi",
"svmax",
"svmin",
"svw",
"turn",
"vb",
"vh",
"vi",
"vmax",
"vmin",
"vw"
]
},
"CSSColor": {
"attributes": [
"alpha",
"channels",
"colorSpace"
],
"methods": []
},
"CSSGroupingRule": {
"attributes": [
"cssRules"
],
"methods": [
"deleteRule",
"insertRule"
]
},
"CSSHSL": {
"attributes": [
"alpha",
"h",
"l",
"s"
],
"methods": []
},
"CSSHWB": {
"attributes": [
"alpha",
"b",
"h",
"w"
],
"methods": []
},
"CSSImportRule": {
"attributes": [
"href",
"layerName",
"media",
"styleSheet",
"supportsText"
],
"methods": []
},
"CSSKeywordValue": {
"attributes": [
"value"
],
"methods": []
},
"CSSLCH": {
"attributes": [
"alpha",
"c",
"h",
"l"
],
"methods": []
},
"CSSLab": {
"attributes": [
"a",
"alpha",
"b",
"l"
],
"methods": []
},
"CSSMarginRule": {
"attributes": [
"name",
"style"
],
"methods": []
},
"CSSMathClamp": {
"attributes": [
"lower",
"upper",
"value"
],
"methods": []
},
"CSSMathInvert": {
"attributes": [
"value"
],
"methods": []
},
"CSSMathMax": {
"attributes": [
"values"
],
"methods": []
},
"CSSMathMin": {
"attributes": [
"values"
],
"methods": []
},
"CSSMathNegate": {
"attributes": [
"value"
],
"methods": []
},
"CSSMathProduct": {
"attributes": [
"values"
],
"methods": []
},
"CSSMathSum": {
"attributes": [
"values"
],
"methods": []
},
"CSSMathValue": {
"attributes": [
"operator"
],
"methods": []
},
"CSSMatrixComponent": {
"attributes": [
"matrix"
],
"methods": []
},
"CSSNamespaceRule": {
"attributes": [
"namespaceURI",
"prefix"
],
"methods": []
},
"CSSNumericArray": {
"attributes": [
"length"
],
"methods": []
},
"CSSNumericValue": {
"attributes": [],
"methods": [
"add",
"div",
"equals",
"max",
"min",
"mul",
"parse",
"sub",
"to",
"toSum",
"type"
]
},
"CSSOKLCH": {
"attributes": [
"alpha",
"c",
"h",
"l"
],
"methods": []
},
"CSSOKLab": {
"attributes": [
"a",
"alpha",
"b",
"l"
],
"methods": []
},
"CSSPageDescriptors": {
"attributes": [
"bleed",
"margin",
"marginBottom",
"marginLeft",
"marginRight",
"marginTop",
"marks",
"pageOrientation",
"size"
],
"methods": []
},
"CSSPageRule": {
"attributes": [
"selectorText",
"style"
],
"methods": []
},
"CSSPerspective": {
"attributes": [
"length"
],
"methods": []
},
"CSSRGB": {
"attributes": [
"alpha",
"b",
"g",
"r"
],
"methods": []
},
"CSSRotate": {
"attributes": [
"angle",
"x",
"y",
"z"
],
"methods": []
},
"CSSRule": {
"attributes": [
"cssText",
"parentRule",
"parentStyleSheet",
"type"
],
"methods": []
},
"CSSRuleList": {
"attributes": [
"length"
],
"methods": [
"item"
]
},
"CSSScale": {
"attributes": [
"x",
"y",
"z"
],
"methods": []
},
"CSSSkew": {
"attributes": [
"ax",
"ay"
],
"methods": []
},
"CSSSkewX": {
"attributes": [
"ax"
],
"methods": []
},
"CSSSkewY": {
"attributes": [
"ay"
],
"methods": []
},
"CSSStyleDeclaration": {
"attributes": [
"cssText",
"length",
"parentRule"
],
"methods": [
"getPropertyPriority",
"getPropertyValue",
"item",
"removeProperty",
"setProperty"
]
},
"CSSStyleProperties": {
"attributes": [
"cssFloat"
],
"methods": []
},
"CSSStyleRule": {
"attributes": [
"selectorText",
"style",
"styleMap"
],
"methods": []
},
"CSSStyleSheet": {
"attributes": [
"cssRules",
"ownerRule",
"rules"
],
"methods": [
"addRule",
"deleteRule",
"insertRule",
"removeRule",
"replace",
"replaceSync"
]
},
"CSSStyleValue": {
"attributes": [],
"methods": [
"parse",
"parseAll"
]
},
"CSSTransformComponent": {
"attributes": [
"is2D"
],
"methods": [
"toMatrix"
]
},
"CSSTransformValue": {
"attributes": [
"is2D",
"length"
],
"methods": [
"toMatrix"
]
},
"CSSTranslate": {
"attributes": [
"x",
"y",
"z"
],
"methods": []
},
"CSSUnitValue": {
"attributes": [
"unit",
"value"
],
"methods": []
},
"CSSUnparsedValue": {
"attributes": [
"length"
],
"methods": []
},
"CSSVariableReferenceValue": {
"attributes": [
"fallback",
"variable"
],
"methods": []
},
"CanvasCompositing": {
"attributes": [
"globalAlpha",
"globalCompositeOperation"
],
"methods": []
},
"CanvasDrawImage": {
"attributes": [],
"methods": [
"drawImage"
]
},
"CanvasDrawPath": {
"attributes": [],
"methods": [
"beginPath",
"clip",
"fill",
"isPointInPath",
"isPointInStroke",
"stroke"
]
},
"CanvasFillStrokeStyles": {
"attributes": [],
"methods": [
"createConicGradient",
"createLinearGradient",
"createPattern",
"createRadialGradient"
]
},
"CanvasFilters": {
"attributes": [
"filter"
],
"methods": []
},
"CanvasGradient": {
"attributes": [],
"methods": [
"addColorStop"
]
},
"CanvasImageData": {
"attributes": [],
"methods": [
"createImageData",
"getImageData",
"putImageData"
]
},
"CanvasImageSmoothing": {
"attributes": [
"imageSmoothingEnabled",
"imageSmoothingQuality"
],
"methods": []
},
"CanvasPath": {
"attributes": [],
"methods": [
"arc",
"arcTo",
"bezierCurveTo",
"closePath",
"ellipse",
"lineTo",
"moveTo",
"quadraticCurveTo",
"rect",
"roundRect"
]
},
"CanvasPathDrawingStyles": {
"attributes": [
"lineCap",
"lineDashOffset",
"lineJoin",
"lineWidth",
"miterLimit"
],
"methods": [
"getLineDash",
"setLineDash"
]
},
"CanvasPattern": {
"attributes": [],
"methods": [
"setTransform"
]
},
"CanvasRect": {
"attributes": [],
"methods": [
"clearRect",
"fillRect",
"strokeRect"
]
},
"CanvasRenderingContext2D": {
"attributes": [
"canvas",
"direction",
"filter",
"font",
"fontKerning",
"fontStretch",
"fontVariantCaps",
"globalAlpha",
"globalCompositeOperation",
"imageSmoothingEnabled",
"imageSmoothingQuality",
"lang",
"letterSpacing",
"lineCap",
"lineDashOffset",
"lineJoin",
"lineWidth",
"miterLimit",
"shadowBlur",
"shadowColor",
"shadowOffsetX",
"shadowOffsetY",
"textAlign",
"textBaseline",
"textRendering",
"wordSpacing"
],
"methods": [
"arc",
"arcTo",
"beginPath",
"bezierCurveTo",
"clearRect",
"clip",
"closePath",
"createConicGradient",
"createImageData",
"createLinearGradient",
"createPattern",
"createRadialGradient",
"drawFocusIfNeeded",
"drawImage",
"ellipse",
"fill",
"fillRect",
"fillText",
"getContextAttributes",
"getImageData",
"getLineDash",
"getTransform",
"isContextLost",
"isPointInPath",
"isPointInStroke",
"lineTo",
"measureText",
"moveTo",
"putImageData",
"quadraticCurveTo",
"rect",
"reset",
"resetTransform",
"restore",
"rotate",
"roundRect",
"save",
"scale",
"setLineDash",
"setTransform",
"stroke",
"strokeRect",
"strokeText",
"transform",
"translate"
]
},
"CanvasSettings": {
"attributes": [],
"methods": [
"getContextAttributes"
]
},
"CanvasShadowStyles": {
"attributes": [
"shadowBlur",
"shadowColor",
"shadowOffsetX",
"shadowOffsetY"
],
"methods": []
},
"CanvasState": {
"attributes": [],
"methods": [
"isContextLost",
"reset",
"restore",
"save"
]
},
"CanvasText": {
"attributes": [],
"methods": [
"fillText",
"measureText",
"strokeText"
]
},
"CanvasTextDrawingStyles": {
"attributes": [
"direction",
"font",
"fontKerning",
"fontStretch",
"fontVariantCaps",
"lang",
"letterSpacing",
"textAlign",
"textBaseline",
"textRendering",
"wordSpacing"
],
"methods": []
},
"CanvasTransform": {
"attributes": [],
"methods": [
"getTransform",
"resetTransform",
"rotate",
"scale",
"setTransform",
"transform",
"translate"
]
},
"CanvasUserInterface": {
"attributes": [],
"methods": [
"drawFocusIfNeeded"
]
},
"CaretPosition": {
"attributes": [
"offset",
"offsetNode"
],
"methods": [
"getClientRect"
]
},
"CharacterData": {
"attributes": [
"data",
"length",
"nextElementSibling",
"previousElementSibling"
],
"methods": [
"after",
"appendData",
"before",
"deleteData",
"insertData",
"remove",
"replaceData",
"replaceWith",
"substringData"
]
},
"ChildNode": {
"attributes": [],
"methods": [
"after",
"before",
"remove",
"replaceWith"
]
},
"Clipboard": {
"attributes": [],
"methods": [
"read",
"readText",
"write",
"writeText"
]
},
"ClipboardChangeEvent": {
"attributes": [
"changeId",
"types"
],
"methods": []
},
"ClipboardEvent": {
"attributes": [
"clipboardData"
],
"methods": []
},
"ClipboardItem": {
"attributes": [
"presentationStyle",
"types"
],
"methods": [
"getType",
"supports"
]
},
"CloseEvent": {
"attributes": [
"code",
"reason",
"wasClean"
],
"methods": []
},
"CloseWatcher": {
"attributes": [
"oncancel",
"onclose"
],
"methods": [
"close",
"destroy",
"requestClose"
]
},
"CommandEvent": {
"attributes": [
"command",
"source"
],
"methods": []
},
"CompositionEvent": {
"attributes": [
"data"
],
"methods": [
"initCompositionEvent"
]
},
"CompressionStream": {
"attributes": [
"readable",
"writable"
],
"methods": []
},
"CountQueuingStrategy": {
"attributes": [
"highWaterMark",
"size"
],
"methods": []
},
"CustomElementRegistry": {
"attributes": [],
"methods": [
"define",
"getName",
"initialize",
"upgrade",
"whenDefined"
]
},
"CustomEvent": {
"attributes": [
"detail"
],
"methods": [
"initCustomEvent"
]
},
"DOMException": {
"attributes": [
"code",
"message",
"name"
],
"methods": []
},
"DOMImplementation": {
"attributes": [],
"methods": [
"createDocument",
"createDocumentType",
"createHTMLDocument",
"hasFeature"
]
},
"DOMParser": {
"attributes": [],
"methods": [
"parseFromString"
]
},
"DOMStringList": {
"attributes": [
"length"
],
"methods": [
"contains",
"item"
]
},
"DOMTokenList": {
"attributes": [
"length",
"value"
],
"methods": [
"add",
"contains",
"item",
"remove",
"replace",
"supports",
"toggle"
]
},
"DataTransfer": {
"attributes": [
"dropEffect",
"effectAllowed",
"files",
"items",
"types"
],
"methods": [
"clearData",
"getData",
"setData",
"setDragImage"
]
},
"DataTransferItem": {
"attributes": [
"kind",
"type"
],
"methods": [
"getAsFile",
"getAsString"
]
},
"DataTransferItemList": {
"attributes": [
"length"
],
"methods": [
"add",
"clear",
"remove"
]
},
"DecompressionStream": {
"attributes": [
"readable",
"writable"
],
"methods": []
},
"DedicatedWorkerGlobalScope": {
"attributes": [
"name",
"onmessage",
"onmessageerror"
],
"methods": [
"cancelAnimationFrame",
"close",
"postMessage",
"requestAnimationFrame"
]
},
"Document": {
"attributes": [
"activeElement",
"adoptedStyleSheets",
"alinkColor",
"all",
"anchors",
"applets",
"bgColor",
"body",
"characterSet",
"charset",
"childElementCount",
"children",
"compatMode",
"contentType",
"cookie",
"currentScript",
"customElementRegistry",
"defaultView",
"designMode",
"dir",
"doctype",
"documentElement",
"documentURI",
"domain",
"embeds",
"fgColor",
"firstElementChild",
"fonts",
"forms",
"fullscreen",
"fullscreenElement",
"fullscreenEnabled",
"head",
"hidden",
"images",
"implementation",
"inputEncoding",
"lastElementChild",
"lastModified",
"linkColor",
"links",
"location",
"onabort",
"onauxclick",
"onbeforeinput",
"onbeforematch",
"onbeforetoggle",
"onblur",
"oncancel",
"oncanplay",
"oncanplaythrough",
"onchange",
"onclick",
"onclose",
"oncommand",
"oncontextlost",
"oncontextmenu",
"oncontextrestored",
"oncopy",
"oncuechange",
"oncut",
"ondblclick",
"ondrag",
"ondragend",
"ondragenter",
"ondragleave",
"ondragover",
"ondragstart",
"ondrop",
"ondurationchange",
"onemptied",
"onended",
"onerror",
"onfocus",
"onformdata",
"onfullscreenchange",
"onfullscreenerror",
"ongotpointercapture",
"oninput",
"oninvalid",
"onkeydown",
"onkeypress",
"onkeyup",
"onload",
"onloadeddata",
"onloadedmetadata",
"onloadstart",
"onlostpointercapture",
"onmousedown",
"onmouseenter",
"onmouseleave",
"onmousemove",
"onmouseout",
"onmouseover",
"onmouseup",
"onpaste",
"onpause",
"onplay",
"onplaying",
"onpointercancel",
"onpointerdown",
"onpointerenter",
"onpointerleave",
"onpointermove",
"onpointerout",
"onpointerover",
"onpointerrawupdate",
"onpointerup",
"onprogress",
"onratechange",
"onreadystatechange",
"onreset",
"onresize",
"onscroll",
"onscrollend",
"onsecuritypolicyviolation",
"onseeked",
"onseeking",
"onselect",
"onselectionchange",
"onselectstart",
"onslotchange",
"onstalled",
"onsubmit",
"onsuspend",
"ontimeupdate",
"ontoggle",
"ontouchcancel",
"ontouchend",
"ontouchmove",
"ontouchstart",
"onvisibilitychange",
"onvolumechange",
"onwaiting",
"onwebkitanimationend",
"onwebkitanimationiteration",
"onwebkitanimationstart",
"onwebkittransitionend",
"onwheel",
"plugins",
"readyState",
"referrer",
"scripts",
"scrollingElement",
"styleSheets",
"timeline",
"title",
"visibilityState",
"vlinkColor"
],
"methods": [
"adoptNode",
"append",
"captureEvents",
"caretPositionFromPoint",
"clear",
"close",
"convertPointFromNode",
"convertQuadFromNode",
"convertRectFromNode",
"createAttribute",
"createAttributeNS",
"createCDATASection",
"createComment",
"createDocumentFragment",
"createElement",
"createElementNS",
"createEvent",
"createExpression",
"createNSResolver",
"createNodeIterator",
"createProcessingInstruction",
"createRange",
"createTextNode",
"createTreeWalker",
"elementFromPoint",
"elementsFromPoint",
"evaluate",
"execCommand",
"exitFullscreen",
"getAnimations",
"getBoxQuads",
"getElementById",
"getElementsByClassName",
"getElementsByName",
"getElementsByTagName",
"getElementsByTagNameNS",
"getSelection",
"hasFocus",
"importNode",
"moveBefore",
"open",
"parseHTML",
"parseHTMLUnsafe",
"prepend",
"queryCommandEnabled",
"queryCommandIndeterm",
"queryCommandState",
"queryCommandSupported",
"queryCommandValue",
"querySelector",
"querySelectorAll",
"releaseEvents",
"replaceChildren",
"write",
"writeln"
]
},
"DocumentFragment": {
"attributes": [
"childElementCount",
"children",
"firstElementChild",
"lastElementChild"
],
"methods": [
"append",
"getElementById",
"moveBefore",
"prepend",
"querySelector",
"querySelectorAll",
"replaceChildren"
]
},
"DocumentOrShadowRoot": {
"attributes": [
"activeElement",
"adoptedStyleSheets",
"customElementRegistry",
"fullscreenElement",
"styleSheets"
],
"methods": [
"getAnimations"
]
},
"DocumentType": {
"attributes": [
"name",
"publicId",
"systemId"
],
"methods": [
"after",
"before",
"remove",
"replaceWith"
]
},
"DragEvent": {
"attributes": [
"dataTransfer"
],
"methods": []
},
"Element": {
"attributes": [
"assignedSlot",
"attributes",
"childElementCount",
"children",
"classList",
"className",
"clientHeight",
"clientLeft",
"clientTop",
"clientWidth",
"currentCSSZoom",
"customElementRegistry",
"firstElementChild",
"id",
"lastElementChild",
"localName",
"namespaceURI",
"nextElementSibling",
"onfullscreenchange",
"onfullscreenerror",
"prefix",
"previousElementSibling",
"scrollHeight",
"scrollLeft",
"scrollTop",
"scrollWidth",
"shadowRoot",
"slot",
"tagName"
],
"methods": [
"after",
"animate",
"append",
"attachShadow",
"before",
"checkVisibility",
"closest",
"computedStyleMap",
"convertPointFromNode",
"convertQuadFromNode",
"convertRectFromNode",
"getAnimations",
"getAttribute",
"getAttributeNS",
"getAttributeNames",
"getAttributeNode",
"getAttributeNodeNS",
"getBoundingClientRect",
"getBoxQuads",
"getClientRects",
"getElementsByClassName",
"getElementsByTagName",
"getElementsByTagNameNS",
"getHTML",
"hasAttribute",
"hasAttributeNS",
"hasAttributes",
"hasPointerCapture",
"insertAdjacentElement",
"insertAdjacentHTML",
"insertAdjacentText",
"matches",
"moveBefore",
"prepend",
"querySelector",
"querySelectorAll",
"releasePointerCapture",
"remove",
"removeAttribute",
"removeAttributeNS",
"removeAttributeNode",
"replaceChildren",
"replaceWith",
"requestFullscreen",
"scroll",
"scrollBy",
"scrollIntoView",
"scrollTo",
"setAttribute",
"setAttributeNS",
"setAttributeNode",
"setAttributeNodeNS",
"setHTML",
"setHTMLUnsafe",
"setPointerCapture",
"toggleAttribute",
"webkitMatchesSelector"
]
},
"ElementCSSInlineStyle": {
"attributes": [
"attributeStyleMap",
"style"
],
"methods": []
},
"ElementContentEditable": {
"attributes": [
"contentEditable",
"enterKeyHint",
"inputMode",
"isContentEditable"
],
"methods": []
},
"ElementInternals": {
"attributes": [
"form",
"labels",
"shadowRoot",
"states",
"validationMessage",
"validity",
"willValidate"
],
"methods": [
"checkValidity",
"reportValidity",
"setFormValue",
"setValidity"
]
},
"ErrorEvent": {
"attributes": [
"colno",
"error",
"filename",
"lineno",
"message"
],
"methods": []
},
"Event": {
"attributes": [
"bubbles",
"cancelBubble",
"cancelable",
"composed",
"currentTarget",
"defaultPrevented",
"eventPhase",
"isTrusted",
"returnValue",
"srcElement",
"target",
"timeStamp",
"type"
],
"methods": [
"composedPath",
"initEvent",
"preventDefault",
"stopImmediatePropagation",
"stopPropagation"
]
},
"EventListener": {
"attributes": [],
"methods": [
"handleEvent"
]
},
"EventSource": {
"attributes": [
"onerror",
"onmessage",
"onopen",
"readyState",
"url",
"withCredentials"
],
"methods": [
"close"
]
},
"EventTarget": {
"attributes": [],
"methods": [
"addEventListener",
"dispatchEvent",
"removeEventListener"
]
},
"FetchLaterResult": {
"attributes": [
"activated"
],
"methods": []
},
"File": {
"attributes": [
"lastModified",
"name"
],
"methods": []
},
"FileList": {
"attributes": [
"length"
],
"methods": [
"item"
]
},
"FileReader": {
"attributes": [
"error",
"onabort",
"onerror",
"onload",
"onloadend",
"onloadstart",
"onprogress",
"readyState"
],
"methods": [
"abort",
"readAsArrayBuffer",
"readAsBinaryString",
"readAsDataURL",
"readAsText"
]
},
"FileReaderSync": {
"attributes": [],
"methods": [
"readAsArrayBuffer",
"readAsBinaryString",
"readAsDataURL",
"readAsText"
]
},
"FocusEvent": {
"attributes": [
"relatedTarget"
],
"methods": []
},
"FontFace": {
"attributes": [
"ascentOverride",
"descentOverride",
"display",
"family",
"featureSettings",
"features",
"lineGapOverride",
"loaded",
"palettes",
"status",
"stretch",
"style",
"unicodeRange",
"variationSettings",
"variations",
"weight"
],
"methods": [
"load"
]
},
"FontFacePalette": {
"attributes": [
"length",
"usableWithDarkBackground",
"usableWithLightBackground"
],
"methods": []
},
"FontFacePalettes": {
"attributes": [
"length"
],
"methods": []
},
"FontFaceSet": {
"attributes": [
"onloading",
"onloadingdone",
"onloadingerror",
"ready",
"status"
],
"methods": [
"add",
"check",
"clear",
"delete",
"load"
]
},
"FontFaceSetLoadEvent": {
"attributes": [
"fontfaces"
],
"methods": []
},
"FontFaceSource": {
"attributes": [
"fonts"
],
"methods": []
},
"FontFaceVariationAxis": {
"attributes": [
"axisTag",
"defaultValue",
"maximumValue",
"minimumValue",
"name"
],
"methods": []
},
"FormData": {
"attributes": [],
"methods": [
"append",
"delete",
"get",
"getAll",
"has",
"set"
]
},
"FormDataEvent": {
"attributes": [
"formData"
],
"methods": []
},
"Gamepad": {
"attributes": [
"axes",
"buttons",
"connected",
"id",
"index",
"mapping",
"timestamp",
"touches",
"vibrationActuator"
],
"methods": []
},
"GamepadButton": {
"attributes": [
"pressed",
"touched",
"value"
],
"methods": []
},
"GamepadEvent": {
"attributes": [
"gamepad"
],
"methods": []
},
"GamepadHapticActuator": {
"attributes": [
"effects"
],
"methods": [
"playEffect",
"reset"
]
},
"GenericTransformStream": {
"attributes": [
"readable",
"writable"
],
"methods": []
},
"GeometryUtils": {
"attributes": [],
"methods": [
"convertPointFromNode",
"convertQuadFromNode",
"convertRectFromNode",
"getBoxQuads"
]
},
"GlobalEventHandlers": {
"attributes": [
"onabort",
"onauxclick",
"onbeforeinput",
"onbeforematch",
"onbeforetoggle",
"onblur",
"oncancel",
"oncanplay",
"oncanplaythrough",
"onchange",
"onclick",
"onclose",
"oncommand",
"oncontextlost",
"oncontextmenu",
"oncontextrestored",
"oncopy",
"oncuechange",
"oncut",
"ondblclick",
"ondrag",
"ondragend",
"ondragenter",
"ondragleave",
"ondragover",
"ondragstart",
"ondrop",
"ondurationchange",
"onemptied",
"onended",
"onerror",
"onfocus",
"onformdata",
"ongotpointercapture",
"oninput",
"oninvalid",
"onkeydown",
"onkeypress",
"onkeyup",
"onload",
"onloadeddata",
"onloadedmetadata",
"onloadstart",
"onlostpointercapture",
"onmousedown",
"onmouseenter",
"onmouseleave",
"onmousemove",
"onmouseout",
"onmouseover",
"onmouseup",
"onpaste",
"onpause",
"onplay",
"onplaying",
"onpointercancel",
"onpointerdown",
"onpointerenter",
"onpointerleave",
"onpointermove",
"onpointerout",
"onpointerover",
"onpointerrawupdate",
"onpointerup",
"onprogress",
"onratechange",
"onreset",
"onresize",
"onscroll",
"onscrollend",
"onsecuritypolicyviolation",
"onseeked",
"onseeking",
"onselect",
"onselectionchange",
"onselectstart",
"onslotchange",
"onstalled",
"onsubmit",
"onsuspend",
"ontimeupdate",
"ontoggle",
"ontouchcancel",
"ontouchend",
"ontouchmove",
"ontouchstart",
"onvolumechange",
"onwaiting",
"onwebkitanimationend",
"onwebkitanimationiteration",
"onwebkitanimationstart",
"onwebkittransitionend",
"onwheel"
],
"methods": []
},
"HTMLAllCollection": {
"attributes": [
"length"
],
"methods": []
},
"HTMLAnchorElement": {
"attributes": [
"charset",
"coords",
"download",
"hash",
"host",
"hostname",
"href",
"hreflang",
"name",
"origin",
"password",
"pathname",
"ping",
"port",
"protocol",
"referrerPolicy",
"rel",
"relList",
"rev",
"search",
"shape",
"target",
"text",
"type",
"username"
],
"methods": []
},
"HTMLAreaElement": {
"attributes": [
"alt",
"coords",
"download",
"hash",
"host",
"hostname",
"href",
"hreflang",
"noHref",
"origin",
"password",
"pathname",
"ping",
"port",
"protocol",
"referrerPolicy",
"rel",
"relList",
"search",
"shape",
"target",
"type",
"username"
],
"methods": []
},
"HTMLBRElement": {
"attributes": [
"clear"
],
"methods": []
},
"HTMLBaseElement": {
"attributes": [
"href",
"target"
],
"methods": []
},
"HTMLBodyElement": {
"attributes": [
"aLink",
"background",
"bgColor",
"link",
"onafterprint",
"onbeforeprint",
"onbeforeunload",
"ongamepadconnected",
"ongamepaddisconnected",
"onhashchange",
"onlanguagechange",
"onmessage",
"onmessageerror",
"onoffline",
"ononline",
"onpagehide",
"onpagereveal",
"onpageshow",
"onpageswap",
"onpopstate",
"onrejectionhandled",
"onstorage",
"onunhandledrejection",
"onunload",
"text",
"vLink"
],
"methods": []
},
"HTMLButtonElement": {
"attributes": [
"command",
"commandForElement",
"disabled",
"form",
"formAction",
"formEnctype",
"formMethod",
"formNoValidate",
"formTarget",
"labels",
"name",
"popoverTargetAction",
"popoverTargetElement",
"type",
"validationMessage",
"validity",
"value",
"willValidate"
],
"methods": [
"checkValidity",
"reportValidity",
"setCustomValidity"
]
},
"HTMLCanvasElement": {
"attributes": [
"height",
"width"
],
"methods": [
"getContext",
"toBlob",
"toDataURL",
"transferControlToOffscreen"
]
},
"HTMLCollection": {
"attributes": [
"length"
],
"methods": [
"item",
"namedItem"
]
},
"HTMLDListElement": {
"attributes": [
"compact"
],
"methods": []
},
"HTMLDataElement": {
"attributes": [
"value"
],
"methods": []
},
"HTMLDataListElement": {
"attributes": [
"options"
],
"methods": []
},
"HTMLDetailsElement": {
"attributes": [
"name",
"open"
],
"methods": []
},
"HTMLDialogElement": {
"attributes": [
"closedBy",
"open",
"returnValue"
],
"methods": [
"close",
"requestClose",
"show",
"showModal"
]
},
"HTMLDirectoryElement": {
"attributes": [
"compact"
],
"methods": []
},
"HTMLDivElement": {
"attributes": [
"align"
],
"methods": []
},
"HTMLElement": {
"attributes": [
"accessKey",
"accessKeyLabel",
"attributeStyleMap",
"autocapitalize",
"autocorrect",
"autofocus",
"contentEditable",
"dataset",
"dir",
"draggable",
"enterKeyHint",
"headingOffset",
"headingReset",
"inert",
"innerText",
"inputMode",
"isContentEditable",
"lang",
"nonce",
"offsetHeight",
"offsetLeft",
"offsetParent",
"offsetTop",
"offsetWidth",
"onabort",
"onauxclick",
"onbeforeinput",
"onbeforematch",
"onbeforetoggle",
"onblur",
"oncancel",
"oncanplay",
"oncanplaythrough",
"onchange",
"onclick",
"onclose",
"oncommand",
"oncontextlost",
"oncontextmenu",
"oncontextrestored",
"oncopy",
"oncuechange",
"oncut",
"ondblclick",
"ondrag",
"ondragend",
"ondragenter",
"ondragleave",
"ondragover",
"ondragstart",
"ondrop",
"ondurationchange",
"onemptied",
"onended",
"onerror",
"onfocus",
"onformdata",
"ongotpointercapture",
"oninput",
"oninvalid",
"onkeydown",
"onkeypress",
"onkeyup",
"onload",
"onloadeddata",
"onloadedmetadata",
"onloadstart",
"onlostpointercapture",
"onmousedown",
"onmouseenter",
"onmouseleave",
"onmousemove",
"onmouseout",
"onmouseover",
"onmouseup",
"onpaste",
"onpause",
"onplay",
"onplaying",
"onpointercancel",
"onpointerdown",
"onpointerenter",
"onpointerleave",
"onpointermove",
"onpointerout",
"onpointerover",
"onpointerrawupdate",
"onpointerup",
"onprogress",
"onratechange",
"onreset",
"onresize",
"onscroll",
"onscrollend",
"onsecuritypolicyviolation",
"onseeked",
"onseeking",
"onselect",
"onselectionchange",
"onselectstart",
"onslotchange",
"onstalled",
"onsubmit",
"onsuspend",
"ontimeupdate",
"ontoggle",
"ontouchcancel",
"ontouchend",
"ontouchmove",
"ontouchstart",
"onvolumechange",
"onwaiting",
"onwebkitanimationend",
"onwebkitanimationiteration",
"onwebkitanimationstart",
"onwebkittransitionend",
"onwheel",
"outerText",
"popover",
"scrollParent",
"spellcheck",
"style",
"tabIndex",
"title",
"translate",
"writingSuggestions"
],
"methods": [
"attachInternals",
"blur",
"click",
"focus",
"hidePopover",
"showPopover",
"togglePopover"
]
},
"HTMLEmbedElement": {
"attributes": [
"align",
"height",
"name",
"src",
"type",
"width"
],
"methods": [
"getSVGDocument"
]
},
"HTMLFieldSetElement": {
"attributes": [
"disabled",
"elements",
"form",
"name",
"type",
"validationMessage",
"validity",
"willValidate"
],
"methods": [
"checkValidity",
"reportValidity",
"setCustomValidity"
]
},
"HTMLFontElement": {
"attributes": [
"color",
"face",
"size"
],
"methods": []
},
"HTMLFormElement": {
"attributes": [
"acceptCharset",
"action",
"autocomplete",
"elements",
"encoding",
"enctype",
"length",
"method",
"name",
"noValidate",
"rel",
"relList",
"target"
],
"methods": [
"checkValidity",
"reportValidity",
"requestSubmit",
"reset",
"submit"
]
},
"HTMLFrameElement": {
"attributes": [
"contentDocument",
"contentWindow",
"frameBorder",
"longDesc",
"marginHeight",
"marginWidth",
"name",
"noResize",
"scrolling",
"src"
],
"methods": []
},
"HTMLFrameSetElement": {
"attributes": [
"cols",
"onafterprint",
"onbeforeprint",
"onbeforeunload",
"ongamepadconnected",
"ongamepaddisconnected",
"onhashchange",
"onlanguagechange",
"onmessage",
"onmessageerror",
"onoffline",
"ononline",
"onpagehide",
"onpagereveal",
"onpageshow",
"onpageswap",
"onpopstate",
"onrejectionhandled",
"onstorage",
"onunhandledrejection",
"onunload",
"rows"
],
"methods": []
},
"HTMLHRElement": {
"attributes": [
"align",
"color",
"noShade",
"size",
"width"
],
"methods": []
},
"HTMLHeadingElement": {
"attributes": [
"align"
],
"methods": []
},
"HTMLHtmlElement": {
"attributes": [
"version"
],
"methods": []
},
"HTMLHyperlinkElementUtils": {
"attributes": [
"href",
"target"
],
"methods": []
},
"HTMLIFrameElement": {
"attributes": [
"align",
"allow",
"allowFullscreen",
"contentDocument",
"contentWindow",
"frameBorder",
"height",
"loading",
"longDesc",
"marginHeight",
"marginWidth",
"name",
"referrerPolicy",
"sandbox",
"scrolling",
"src",
"width"
],
"methods": [
"getSVGDocument"
]
},
"HTMLImageElement": {
"attributes": [
"align",
"alt",
"border",
"complete",
"controls",
"crossOrigin",
"currentSrc",
"decoding",
"fetchPriority",
"height",
"hspace",
"isMap",
"loading",
"longDesc",
"lowsrc",
"name",
"naturalHeight",
"naturalWidth",
"referrerPolicy",
"sizes",
"src",
"srcset",
"useMap",
"vspace",
"width",
"x",
"y"
],
"methods": [
"decode"
]
},
"HTMLInputElement": {
"attributes": [
"accept",
"align",
"alpha",
"alt",
"autocomplete",
"checked",
"colorSpace",
"defaultChecked",
"defaultValue",
"dirName",
"disabled",
"files",
"form",
"formAction",
"formEnctype",
"formMethod",
"formNoValidate",
"formTarget",
"height",
"indeterminate",
"labels",
"list",
"max",
"maxLength",
"min",
"minLength",
"multiple",
"name",
"pattern",
"placeholder",
"popoverTargetAction",
"popoverTargetElement",
"readOnly",
"selectionDirection",
"selectionEnd",
"selectionStart",
"size",
"src",
"step",
"type",
"useMap",
"validationMessage",
"validity",
"value",
"valueAsDate",
"valueAsNumber",
"width",
"willValidate"
],
"methods": [
"checkValidity",
"reportValidity",
"select",
"setCustomValidity",
"setRangeText",
"setSelectionRange",
"showPicker",
"stepDown",
"stepUp"
]
},
"HTMLLIElement": {
"attributes": [
"type",
"value"
],
"methods": []
},
"HTMLLabelElement": {
"attributes": [
"control",
"form",
"htmlFor"
],
"methods": []
},
"HTMLLegendElement": {
"attributes": [
"align",
"form"
],
"methods": []
},
"HTMLLinkElement": {
"attributes": [
"as",
"blocking",
"charset",
"crossOrigin",
"disabled",
"fetchPriority",
"href",
"hreflang",
"imageSizes",
"imageSrcset",
"integrity",
"media",
"referrerPolicy",
"rel",
"relList",
"rev",
"sheet",
"sizes",
"target",
"type"
],
"methods": []
},
"HTMLMapElement": {
"attributes": [
"areas",
"name"
],
"methods": []
},
"HTMLMarqueeElement": {
"attributes": [
"behavior",
"bgColor",
"direction",
"height",
"hspace",
"loop",
"scrollAmount",
"scrollDelay",
"trueSpeed",
"vspace",
"width"
],
"methods": [
"start",
"stop"
]
},
"HTMLMediaElement": {
"attributes": [
"audioTracks",
"autoplay",
"buffered",
"controls",
"crossOrigin",
"currentSrc",
"currentTime",
"defaultMuted",
"defaultPlaybackRate",
"duration",
"ended",
"error",
"loading",
"loop",
"muted",
"networkState",
"paused",
"playbackRate",
"played",
"preload",
"preservesPitch",
"readyState",
"seekable",
"seeking",
"src",
"srcObject",
"textTracks",
"videoTracks",
"volume"
],
"methods": [
"addTextTrack",
"canPlayType",
"fastSeek",
"getStartDate",
"load",
"pause",
"play"
]
},
"HTMLMenuElement": {
"attributes": [
"compact"
],
"methods": []
},
"HTMLMetaElement": {
"attributes": [
"content",
"httpEquiv",
"media",
"name",
"scheme"
],
"methods": []
},
"HTMLMeterElement": {
"attributes": [
"high",
"labels",
"low",
"max",
"min",
"optimum",
"value"
],
"methods": []
},
"HTMLModElement": {
"attributes": [
"cite",
"dateTime"
],
"methods": []
},
"HTMLOListElement": {
"attributes": [
"compact",
"reversed",
"start",
"type"
],
"methods": []
},
"HTMLObjectElement": {
"attributes": [
"align",
"archive",
"border",
"code",
"codeBase",
"codeType",
"contentDocument",
"contentWindow",
"data",
"declare",
"form",
"height",
"hspace",
"name",
"standby",
"type",
"useMap",
"validationMessage",
"validity",
"vspace",
"width",
"willValidate"
],
"methods": [
"checkValidity",
"getSVGDocument",
"reportValidity",
"setCustomValidity"
]
},
"HTMLOptGroupElement": {
"attributes": [
"disabled",
"label"
],
"methods": []
},
"HTMLOptionElement": {
"attributes": [
"defaultSelected",
"disabled",
"form",
"index",
"label",
"selected",
"text",
"value"
],
"methods": []
},
"HTMLOptionsCollection": {
"attributes": [
"length",
"selectedIndex"
],
"methods": [
"add",
"remove"
]
},
"HTMLOrSVGOrMathMLElement": {
"attributes": [
"autofocus",
"dataset",
"nonce",
"tabIndex"
],
"methods": [
"blur",
"focus"
]
},
"HTMLOutputElement": {
"attributes": [
"defaultValue",
"form",
"htmlFor",
"labels",
"name",
"type",
"validationMessage",
"validity",
"value",
"willValidate"
],
"methods": [
"checkValidity",
"reportValidity",
"setCustomValidity"
]
},
"HTMLParagraphElement": {
"attributes": [
"align"
],
"methods": []
},
"HTMLParamElement": {
"attributes": [
"name",
"type",
"value",
"valueType"
],
"methods": []
},
"HTMLPreElement": {
"attributes": [
"width"
],
"methods": []
},
"HTMLProgressElement": {
"attributes": [
"labels",
"max",
"position",
"value"
],
"methods": []
},
"HTMLQuoteElement": {
"attributes": [
"cite"
],
"methods": []
},
"HTMLScriptElement": {
"attributes": [
"async",
"blocking",
"charset",
"crossOrigin",
"defer",
"event",
"fetchPriority",
"htmlFor",
"integrity",
"noModule",
"referrerPolicy",
"src",
"text",
"type"
],
"methods": [
"supports"
]
},
"HTMLSelectElement": {
"attributes": [
"autocomplete",
"disabled",
"form",
"labels",
"length",
"multiple",
"name",
"options",
"selectedIndex",
"selectedOptions",
"size",
"type",
"validationMessage",
"validity",
"value",
"willValidate"
],
"methods": [
"add",
"checkValidity",
"item",
"namedItem",
"remove",
"reportValidity",
"setCustomValidity",
"showPicker"
]
},
"HTMLSlotElement": {
"attributes": [
"name"
],
"methods": [
"assign",
"assignedElements",
"assignedNodes"
]
},
"HTMLSourceElement": {
"attributes": [
"height",
"media",
"sizes",
"src",
"srcset",
"type",
"width"
],
"methods": []
},
"HTMLStyleElement": {
"attributes": [
"blocking",
"disabled",
"media",
"sheet",
"type"
],
"methods": []
},
"HTMLTableCaptionElement": {
"attributes": [
"align"
],
"methods": []
},
"HTMLTableCellElement": {
"attributes": [
"abbr",
"align",
"axis",
"bgColor",
"cellIndex",
"ch",
"chOff",
"colSpan",
"headers",
"height",
"noWrap",
"rowSpan",
"scope",
"vAlign",
"width"
],
"methods": []
},
"HTMLTableColElement": {
"attributes": [
"align",
"ch",
"chOff",
"span",
"vAlign",
"width"
],
"methods": []
},
"HTMLTableElement": {
"attributes": [
"align",
"bgColor",
"border",
"caption",
"cellPadding",
"cellSpacing",
"frame",
"rows",
"rules",
"summary",
"tBodies",
"tFoot",
"tHead",
"width"
],
"methods": [
"createCaption",
"createTBody",
"createTFoot",
"createTHead",
"deleteCaption",
"deleteRow",
"deleteTFoot",
"deleteTHead",
"insertRow"
]
},
"HTMLTableRowElement": {
"attributes": [
"align",
"bgColor",
"cells",
"ch",
"chOff",
"rowIndex",
"sectionRowIndex",
"vAlign"
],
"methods": [
"deleteCell",
"insertCell"
]
},
"HTMLTableSectionElement": {
"attributes": [
"align",
"ch",
"chOff",
"rows",
"vAlign"
],
"methods": [
"deleteRow",
"insertRow"
]
},
"HTMLTemplateElement": {
"attributes": [
"content",
"htmlFor",
"shadowRootClonable",
"shadowRootCustomElementRegistry",
"shadowRootDelegatesFocus",
"shadowRootMode",
"shadowRootSerializable",
"shadowRootSlotAssignment"
],
"methods": []
},
"HTMLTextAreaElement": {
"attributes": [
"autocomplete",
"cols",
"defaultValue",
"dirName",
"disabled",
"form",
"labels",
"maxLength",
"minLength",
"name",
"placeholder",
"readOnly",
"rows",
"selectionDirection",
"selectionEnd",
"selectionStart",
"textLength",
"type",
"validationMessage",
"validity",
"value",
"willValidate",
"wrap"
],
"methods": [
"checkValidity",
"reportValidity",
"select",
"setCustomValidity",
"setRangeText",
"setSelectionRange"
]
},
"HTMLTimeElement": {
"attributes": [
"dateTime"
],
"methods": []
},
"HTMLTitleElement": {
"attributes": [
"text"
],
"methods": []
},
"HTMLTrackElement": {
"attributes": [
"default",
"kind",
"label",
"readyState",
"src",
"srclang",
"track"
],
"methods": []
},
"HTMLUListElement": {
"attributes": [
"compact",
"type"
],
"methods": []
},
"HTMLVideoElement": {
"attributes": [
"height",
"playsInline",
"poster",
"videoHeight",
"videoWidth",
"width"
],
"methods": []
},
"HashChangeEvent": {
"attributes": [
"newURL",
"oldURL"
],
"methods": []
},
"Headers": {
"attributes": [],
"methods": [
"append",
"delete",
"get",
"getSetCookie",
"has",
"set"
]
},
"Highlight": {
"attributes": [
"priority",
"type"
],
"methods": []
},
"HighlightRegistry": {
"attributes": [],
"methods": [
"highlightsFromPoint"
]
},
"History": {
"attributes": [
"length",
"scrollRestoration",
"state"
],
"methods": [
"back",
"forward",
"go",
"pushState",
"replaceState"
]
},
"HyperlinkElementUtils": {
"attributes": [
"hash",
"host",
"hostname",
"hreflang",
"origin",
"password",
"pathname",
"port",
"protocol",
"search",
"type",
"username"
],
"methods": []
},
"IDBCursor": {
"attributes": [
"direction",
"key",
"primaryKey",
"request"
],
"methods": [
"advance",
"continue",
"continuePrimaryKey",
"delete",
"update"
]
},
"IDBCursorWithValue": {
"attributes": [
"value"
],
"methods": []
},
"IDBDatabase": {
"attributes": [
"name",
"objectStoreNames",
"onabort",
"onclose",
"onerror",
"onversionchange",
"version"
],
"methods": [
"close",
"createObjectStore",
"deleteObjectStore",
"transaction"
]
},
"IDBFactory": {
"attributes": [],
"methods": [
"cmp",
"databases",
"deleteDatabase",
"open"
]
},
"IDBIndex": {
"attributes": [
"keyPath",
"multiEntry",
"name",
"objectStore",
"unique"
],
"methods": [
"count",
"get",
"getAll",
"getAllKeys",
"getAllRecords",
"getKey",
"openCursor",
"openKeyCursor"
]
},
"IDBKeyRange": {
"attributes": [
"lower",
"lowerOpen",
"upper",
"upperOpen"
],
"methods": [
"bound",
"lowerBound",
"only",
"upperBound"
]
},
"IDBObjectStore": {
"attributes": [
"autoIncrement",
"indexNames",
"keyPath",
"name",
"transaction"
],
"methods": [
"add",
"clear",
"count",
"createIndex",
"delete",
"deleteIndex",
"get",
"getAll",
"getAllKeys",
"getAllRecords",
"getKey",
"index",
"openCursor",
"openKeyCursor",
"put"
]
},
"IDBOpenDBRequest": {
"attributes": [
"onblocked",
"onupgradeneeded"
],
"methods": []
},
"IDBRecord": {
"attributes": [
"key",
"primaryKey",
"value"
],
"methods": []
},
"IDBRequest": {
"attributes": [
"error",
"onerror",
"onsuccess",
"readyState",
"result",
"transaction"
],
"methods": []
},
"IDBTransaction": {
"attributes": [
"db",
"durability",
"error",
"mode",
"objectStoreNames",
"onabort",
"oncomplete",
"onerror"
],
"methods": [
"abort",
"commit",
"objectStore"
]
},
"IDBVersionChangeEvent": {
"attributes": [
"newVersion",
"oldVersion"
],
"methods": []
},
"IdleDeadline": {
"attributes": [
"didTimeout"
],
"methods": [
"timeRemaining"
]
},
"ImageBitmap": {
"attributes": [
"height",
"width"
],
"methods": [
"close"
]
},
"ImageBitmapRenderingContext": {
"attributes": [],
"methods": [
"transferFromImageBitmap"
]
},
"ImageData": {
"attributes": [
"colorSpace",
"data",
"height",
"pixelFormat",
"width"
],
"methods": []
},
"InputEvent": {
"attributes": [
"data",
"inputType",
"isComposing"
],
"methods": []
},
"IntersectionObserver": {
"attributes": [
"delay",
"rootMargin",
"scrollMargin",
"thresholds",
"trackVisibility"
],
"methods": [
"disconnect",
"observe",
"takeRecords",
"unobserve"
]
},
"IntersectionObserverEntry": {
"attributes": [
"boundingClientRect",
"intersectionRatio",
"intersectionRect",
"isIntersecting",
"isVisible",
"rootBounds",
"target",
"time"
],
"methods": []
},
"KeyboardEvent": {
"attributes": [
"altKey",
"charCode",
"code",
"ctrlKey",
"isComposing",
"key",
"keyCode",
"location",
"metaKey",
"repeat",
"shiftKey"
],
"methods": [
"getModifierState",
"initKeyboardEvent"
]
},
"KeyframeEffect": {
"attributes": [
"composite",
"pseudoElement",
"target"
],
"methods": [
"getKeyframes",
"setKeyframes"
]
},
"LinkStyle": {
"attributes": [
"sheet"
],
"methods": []
},
"Location": {
"attributes": [
"ancestorOrigins",
"hash",
"host",
"hostname",
"href",
"origin",
"pathname",
"port",
"protocol",
"search"
],
"methods": [
"assign",
"reload",
"replace"
]
},
"MediaError": {
"attributes": [
"code",
"message"
],
"methods": []
},
"MediaList": {
"attributes": [
"length",
"mediaText"
],
"methods": [
"appendMedium",
"deleteMedium",
"item"
]
},
"MediaQueryList": {
"attributes": [
"matches",
"media",
"onchange"
],
"methods": [
"addListener",
"removeListener"
]
},
"MediaQueryListEvent": {
"attributes": [
"matches",
"media"
],
"methods": []
},
"MessageChannel": {
"attributes": [
"port1",
"port2"
],
"methods": []
},
"MessageEvent": {
"attributes": [
"data",
"lastEventId",
"origin",
"ports",
"source"
],
"methods": [
"initMessageEvent"
]
},
"MessageEventTarget": {
"attributes": [
"onmessage",
"onmessageerror"
],
"methods": []
},
"MessagePort": {
"attributes": [
"onclose",
"onmessage",
"onmessageerror"
],
"methods": [
"close",
"postMessage",
"start"
]
},
"MimeType": {
"attributes": [
"description",
"enabledPlugin",
"suffixes",
"type"
],
"methods": []
},
"MimeTypeArray": {
"attributes": [
"length"
],
"methods": [
"item",
"namedItem"
]
},
"MouseEvent": {
"attributes": [
"altKey",
"button",
"buttons",
"clientX",
"clientY",
"ctrlKey",
"layerX",
"layerY",
"metaKey",
"offsetX",
"offsetY",
"pageX",
"pageY",
"relatedTarget",
"screenX",
"screenY",
"shiftKey",
"x",
"y"
],
"methods": [
"getModifierState",
"initMouseEvent"
]
},
"MutationObserver": {
"attributes": [],
"methods": [
"disconnect",
"observe",
"takeRecords"
]
},
"MutationRecord": {
"attributes": [
"addedNodes",
"attributeName",
"attributeNamespace",
"nextSibling",
"oldValue",
"previousSibling",
"removedNodes",
"target",
"type"
],
"methods": []
},
"NamedNodeMap": {
"attributes": [
"length"
],
"methods": [
"getNamedItem",
"getNamedItemNS",
"item",
"removeNamedItem",
"removeNamedItemNS",
"setNamedItem",
"setNamedItemNS"
]
},
"NavigateEvent": {
"attributes": [
"canIntercept",
"destination",
"downloadRequest",
"formData",
"hasUAVisualTransition",
"hashChange",
"info",
"navigationType",
"signal",
"sourceElement",
"userInitiated"
],
"methods": [
"intercept",
"scroll"
]
},
"Navigation": {
"attributes": [
"activation",
"canGoBack",
"canGoForward",
"currentEntry",
"oncurrententrychange",
"onnavigate",
"onnavigateerror",
"onnavigatesuccess",
"transition"
],
"methods": [
"back",
"entries",
"forward",
"navigate",
"reload",
"traverseTo",
"updateCurrentEntry"
]
},
"NavigationActivation": {
"attributes": [
"entry",
"from",
"navigationType"
],
"methods": []
},
"NavigationCurrentEntryChangeEvent": {
"attributes": [
"from",
"navigationType"
],
"methods": []
},
"NavigationDestination": {
"attributes": [
"id",
"index",
"key",
"sameDocument",
"url"
],
"methods": [
"getState"
]
},
"NavigationHistoryEntry": {
"attributes": [
"id",
"index",
"key",
"ondispose",
"sameDocument",
"url"
],
"methods": [
"getState"
]
},
"NavigationPrecommitController": {
"attributes": [],
"methods": [
"addHandler",
"redirect"
]
},
"NavigationTransition": {
"attributes": [
"committed",
"finished",
"from",
"navigationType",
"to"
],
"methods": []
},
"Navigator": {
"attributes": [
"appCodeName",
"appName",
"appVersion",
"clipboard",
"cookieEnabled",
"hardwareConcurrency",
"language",
"languages",
"maxTouchPoints",
"mimeTypes",
"onLine",
"oscpu",
"pdfViewerEnabled",
"platform",
"plugins",
"product",
"productSub",
"storage",
"userActivation",
"userAgent",
"vendor",
"vendorSub"
],
"methods": [
"getBattery",
"getGamepads",
"javaEnabled",
"registerProtocolHandler",
"taintEnabled",
"unregisterProtocolHandler",
"vibrate"
]
},
"NavigatorConcurrentHardware": {
"attributes": [
"hardwareConcurrency"
],
"methods": []
},
"NavigatorContentUtils": {
"attributes": [],
"methods": [
"registerProtocolHandler",
"unregisterProtocolHandler"
]
},
"NavigatorCookies": {
"attributes": [
"cookieEnabled"
],
"methods": []
},
"NavigatorID": {
"attributes": [
"appCodeName",
"appName",
"appVersion",
"oscpu",
"platform",
"product",
"productSub",
"userAgent",
"vendor",
"vendorSub"
],
"methods": [
"taintEnabled"
]
},
"NavigatorLanguage": {
"attributes": [
"language",
"languages"
],
"methods": []
},
"NavigatorOnLine": {
"attributes": [
"onLine"
],
"methods": []
},
"NavigatorPlugins": {
"attributes": [
"mimeTypes",
"pdfViewerEnabled",
"plugins"
],
"methods": [
"javaEnabled"
]
},
"NavigatorStorage": {
"attributes": [
"storage"
],
"methods": []
},
"Node": {
"attributes": [
"baseURI",
"childNodes",
"firstChild",
"isConnected",
"lastChild",
"nextSibling",
"nodeName",
"nodeType",
"nodeValue",
"ownerDocument",
"parentElement",
"parentNode",
"previousSibling",
"textContent"
],
"methods": [
"appendChild",
"cloneNode",
"compareDocumentPosition",
"contains",
"getRootNode",
"hasChildNodes",
"insertBefore",
"isDefaultNamespace",
"isEqualNode",
"isSameNode",
"lookupNamespaceURI",
"lookupPrefix",
"normalize",
"removeChild",
"replaceChild"
]
},
"NodeFilter": {
"attributes": [],
"methods": [
"acceptNode"
]
},
"NodeIterator": {
"attributes": [
"filter",
"pointerBeforeReferenceNode",
"referenceNode",
"root",
"whatToShow"
],
"methods": [
"detach",
"nextNode",
"previousNode"
]
},
"NodeList": {
"attributes": [
"length"
],
"methods": [
"item"
]
},
"NonDocumentTypeChildNode": {
"attributes": [
"nextElementSibling",
"previousElementSibling"
],
"methods": []
},
"NonElementParentNode": {
"attributes": [],
"methods": [
"getElementById"
]
},
"NotRestoredReasonDetails": {
"attributes": [
"reason"
],
"methods": [
"toJSON"
]
},
"NotRestoredReasons": {
"attributes": [
"children",
"id",
"name",
"reasons",
"src",
"url"
],
"methods": [
"toJSON"
]
},
"Notification": {
"attributes": [
"actions",
"badge",
"body",
"data",
"dir",
"icon",
"image",
"lang",
"maxActions",
"navigate",
"onclick",
"onclose",
"onerror",
"onshow",
"permission",
"renotify",
"requireInteraction",
"silent",
"tag",
"timestamp",
"title",
"vibrate"
],
"methods": [
"close",
"requestPermission"
]
},
"NotificationEvent": {
"attributes": [
"action",
"notification"
],
"methods": []
},
"OffscreenCanvas": {
"attributes": [
"height",
"oncontextlost",
"oncontextrestored",
"width"
],
"methods": [
"convertToBlob",
"getContext",
"transferToImageBitmap"
]
},
"OffscreenCanvasRenderingContext2D": {
"attributes": [
"canvas",
"direction",
"filter",
"font",
"fontKerning",
"fontStretch",
"fontVariantCaps",
"globalAlpha",
"globalCompositeOperation",
"imageSmoothingEnabled",
"imageSmoothingQuality",
"lang",
"letterSpacing",
"lineCap",
"lineDashOffset",
"lineJoin",
"lineWidth",
"miterLimit",
"shadowBlur",
"shadowColor",
"shadowOffsetX",
"shadowOffsetY",
"textAlign",
"textBaseline",
"textRendering",
"wordSpacing"
],
"methods": [
"arc",
"arcTo",
"beginPath",
"bezierCurveTo",
"clearRect",
"clip",
"closePath",
"createConicGradient",
"createImageData",
"createLinearGradient",
"createPattern",
"createRadialGradient",
"drawImage",
"ellipse",
"fill",
"fillRect",
"fillText",
"getContextAttributes",
"getImageData",
"getLineDash",
"getTransform",
"isContextLost",
"isPointInPath",
"isPointInStroke",
"lineTo",
"measureText",
"moveTo",
"putImageData",
"quadraticCurveTo",
"rect",
"reset",
"resetTransform",
"restore",
"rotate",
"roundRect",
"save",
"scale",
"setLineDash",
"setTransform",
"stroke",
"strokeRect",
"strokeText",
"transform",
"translate"
]
},
"Origin": {
"attributes": [
"opaque"
],
"methods": [
"from",
"isSameOrigin",
"isSameSite"
]
},
"PageRevealEvent": {
"attributes": [
"viewTransition"
],
"methods": []
},
"PageSwapEvent": {
"attributes": [
"activation",
"viewTransition"
],
"methods": []
},
"PageTransitionEvent": {
"attributes": [
"persisted"
],
"methods": []
},
"ParentNode": {
"attributes": [
"childElementCount",
"children",
"firstElementChild",
"lastElementChild"
],
"methods": [
"append",
"moveBefore",
"prepend",
"querySelector",
"querySelectorAll",
"replaceChildren"
]
},
"Path2D": {
"attributes": [],
"methods": [
"addPath",
"arc",
"arcTo",
"bezierCurveTo",
"closePath",
"ellipse",
"lineTo",
"moveTo",
"quadraticCurveTo",
"rect",
"roundRect"
]
},
"Performance": {
"attributes": [
"navigation",
"timeOrigin",
"timing"
],
"methods": [
"clearMarks",
"clearMeasures",
"getEntries",
"getEntriesByName",
"getEntriesByType",
"mark",
"measure",
"now",
"toJSON"
]
},
"PerformanceEntry": {
"attributes": [
"duration",
"entryType",
"id",
"name",
"navigationId",
"startTime"
],
"methods": [
"toJSON"
]
},
"PerformanceMark": {
"attributes": [
"detail"
],
"methods": []
},
"PerformanceMeasure": {
"attributes": [
"detail"
],
"methods": []
},
"PerformanceNavigation": {
"attributes": [
"redirectCount",
"type"
],
"methods": [
"toJSON"
]
},
"PerformanceNavigationTiming": {
"attributes": [
"confidence",
"criticalCHRestart",
"domComplete",
"domContentLoadedEventEnd",
"domContentLoadedEventStart",
"domInteractive",
"loadEventEnd",
"loadEventStart",
"notRestoredReasons",
"redirectCount",
"type",
"unloadEventEnd",
"unloadEventStart"
],
"methods": [
"toJSON"
]
},
"PerformanceObserver": {
"attributes": [
"supportedEntryTypes"
],
"methods": [
"disconnect",
"observe",
"takeRecords"
]
},
"PerformanceObserverEntryList": {
"attributes": [],
"methods": [
"getEntries",
"getEntriesByName",
"getEntriesByType"
]
},
"PerformanceTiming": {
"attributes": [
"connectEnd",
"connectStart",
"domComplete",
"domContentLoadedEventEnd",
"domContentLoadedEventStart",
"domInteractive",
"domLoading",
"domainLookupEnd",
"domainLookupStart",
"fetchStart",
"loadEventEnd",
"loadEventStart",
"navigationStart",
"redirectEnd",
"redirectStart",
"requestStart",
"responseEnd",
"responseStart",
"secureConnectionStart",
"unloadEventEnd",
"unloadEventStart"
],
"methods": [
"toJSON"
]
},
"PerformanceTimingConfidence": {
"attributes": [
"randomizedTriggerRate",
"value"
],
"methods": [
"toJSON"
]
},
"Plugin": {
"attributes": [
"description",
"filename",
"length",
"name"
],
"methods": [
"item",
"namedItem"
]
},
"PluginArray": {
"attributes": [
"length"
],
"methods": [
"item",
"namedItem",
"refresh"
]
},
"PointerEvent": {
"attributes": [
"altitudeAngle",
"azimuthAngle",
"height",
"isPrimary",
"persistentDeviceId",
"pointerId",
"pointerType",
"pressure",
"tangentialPressure",
"tiltX",
"tiltY",
"twist",
"width"
],
"methods": [
"getCoalescedEvents",
"getPredictedEvents"
]
},
"PopStateEvent": {
"attributes": [
"hasUAVisualTransition",
"state"
],
"methods": []
},
"PopoverTargetAttributes": {
"attributes": [
"popoverTargetAction",
"popoverTargetElement"
],
"methods": []
},
"ProcessingInstruction": {
"attributes": [
"sheet",
"target"
],
"methods": [
"getAttribute",
"getAttributeNames",
"hasAttribute",
"hasAttributes",
"removeAttribute",
"setAttribute",
"toggleAttribute"
]
},
"ProgressEvent": {
"attributes": [
"lengthComputable",
"loaded",
"total"
],
"methods": []
},
"PromiseRejectionEvent": {
"attributes": [
"promise",
"reason"
],
"methods": []
},
"QuotaExceededError": {
"attributes": [
"quota",
"requested"
],
"methods": []
},
"RadioNodeList": {
"attributes": [
"value"
],
"methods": []
},
"Range": {
"attributes": [
"commonAncestorContainer"
],
"methods": [
"cloneContents",
"cloneRange",
"collapse",
"compareBoundaryPoints",
"comparePoint",
"createContextualFragment",
"deleteContents",
"detach",
"extractContents",
"getBoundingClientRect",
"getClientRects",
"insertNode",
"intersectsNode",
"isPointInRange",
"selectNode",
"selectNodeContents",
"setEnd",
"setEndAfter",
"setEndBefore",
"setStart",
"setStartAfter",
"setStartBefore",
"surroundContents"
]
},
"ReadableByteStreamController": {
"attributes": [
"byobRequest",
"desiredSize"
],
"methods": [
"close",
"enqueue",
"error"
]
},
"ReadableStream": {
"attributes": [
"locked"
],
"methods": [
"cancel",
"from",
"getReader",
"pipeThrough",
"pipeTo",
"tee"
]
},
"ReadableStreamBYOBReader": {
"attributes": [
"closed"
],
"methods": [
"cancel",
"read",
"releaseLock"
]
},
"ReadableStreamBYOBRequest": {
"attributes": [
"view"
],
"methods": [
"respond",
"respondWithNewView"
]
},
"ReadableStreamDefaultController": {
"attributes": [
"desiredSize"
],
"methods": [
"close",
"enqueue",
"error"
]
},
"ReadableStreamDefaultReader": {
"attributes": [
"closed"
],
"methods": [
"cancel",
"read",
"releaseLock"
]
},
"ReadableStreamGenericReader": {
"attributes": [
"closed"
],
"methods": [
"cancel"
]
},
"Request": {
"attributes": [
"body",
"bodyUsed",
"cache",
"credentials",
"destination",
"duplex",
"headers",
"integrity",
"isHistoryNavigation",
"isReloadNavigation",
"keepalive",
"method",
"mode",
"redirect",
"referrer",
"referrerPolicy",
"signal",
"url"
],
"methods": [
"arrayBuffer",
"blob",
"bytes",
"clone",
"formData",
"json",
"text",
"textStream"
]
},
"ResizeObserver": {
"attributes": [],
"methods": [
"disconnect",
"observe",
"unobserve"
]
},
"ResizeObserverEntry": {
"attributes": [
"borderBoxSize",
"contentBoxSize",
"contentRect",
"devicePixelContentBoxSize",
"target"
],
"methods": []
},
"ResizeObserverSize": {
"attributes": [
"blockSize",
"inlineSize"
],
"methods": []
},
"Response": {
"attributes": [
"body",
"bodyUsed",
"headers",
"ok",
"redirected",
"status",
"statusText",
"type",
"url"
],
"methods": [
"arrayBuffer",
"blob",
"bytes",
"clone",
"error",
"formData",
"json",
"redirect",
"text",
"textStream"
]
},
"Sanitizer": {
"attributes": [],
"methods": [
"allowAttribute",
"allowElement",
"allowProcessingInstruction",
"get",
"removeAttribute",
"removeElement",
"removeProcessingInstruction",
"removeUnsafe",
"replaceElementWithChildren",
"setComments",
"setDataAttributes"
]
},
"Screen": {
"attributes": [
"availHeight",
"availWidth",
"colorDepth",
"height",
"orientation",
"pixelDepth",
"width"
],
"methods": []
},
"ScreenOrientation": {
"attributes": [
"angle",
"onchange",
"type"
],
"methods": [
"lock",
"unlock"
]
},
"Selection": {
"attributes": [
"anchorNode",
"anchorOffset",
"direction",
"focusNode",
"focusOffset",
"isCollapsed",
"rangeCount",
"type"
],
"methods": [
"addRange",
"collapse",
"collapseToEnd",
"collapseToStart",
"containsNode",
"deleteFromDocument",
"empty",
"extend",
"getComposedRanges",
"getRangeAt",
"modify",
"removeAllRanges",
"removeRange",
"selectAllChildren",
"setBaseAndExtent",
"setPosition"
]
},
"ServiceWorkerGlobalScope": {
"attributes": [
"onnotificationclick",
"onnotificationclose"
],
"methods": []
},
"ServiceWorkerRegistration": {
"attributes": [],
"methods": [
"getNotifications",
"showNotification"
]
},
"ShadowRoot": {
"attributes": [
"activeElement",
"adoptedStyleSheets",
"clonable",
"customElementRegistry",
"delegatesFocus",
"fullscreenElement",
"host",
"mode",
"onslotchange",
"serializable",
"slotAssignment",
"styleSheets"
],
"methods": [
"getAnimations",
"getHTML",
"setHTML",
"setHTMLUnsafe"
]
},
"SharedWorker": {
"attributes": [
"onerror",
"port"
],
"methods": []
},
"SharedWorkerGlobalScope": {
"attributes": [
"name",
"onconnect"
],
"methods": [
"close"
]
},
"Slottable": {
"attributes": [
"assignedSlot"
],
"methods": []
},
"Storage": {
"attributes": [
"length"
],
"methods": [
"clear",
"getItem",
"key",
"removeItem",
"setItem"
]
},
"StorageEvent": {
"attributes": [
"key",
"newValue",
"oldValue",
"storageArea",
"url"
],
"methods": [
"initStorageEvent"
]
},
"StorageManager": {
"attributes": [],
"methods": [
"estimate",
"persist",
"persisted"
]
},
"StylePropertyMap": {
"attributes": [],
"methods": [
"append",
"clear",
"delete",
"set"
]
},
"StylePropertyMapReadOnly": {
"attributes": [
"size"
],
"methods": [
"getAll",
"has"
]
},
"StyleSheet": {
"attributes": [
"disabled",
"href",
"media",
"parentStyleSheet",
"title",
"type"
],
"methods": []
},
"StyleSheetList": {
"attributes": [
"length"
],
"methods": [
"item"
]
},
"SubmitEvent": {
"attributes": [
"submitter"
],
"methods": []
},
"Text": {
"attributes": [
"assignedSlot",
"wholeText"
],
"methods": [
"convertPointFromNode",
"convertQuadFromNode",
"convertRectFromNode",
"getBoxQuads",
"splitText"
]
},
"TextDecoder": {
"attributes": [
"encoding",
"fatal",
"ignoreBOM"
],
"methods": [
"decode"
]
},
"TextDecoderCommon": {
"attributes": [
"encoding",
"fatal",
"ignoreBOM"
],
"methods": []
},
"TextDecoderStream": {
"attributes": [
"encoding",
"fatal",
"ignoreBOM",
"readable",
"writable"
],
"methods": []
},
"TextEncoder": {
"attributes": [
"encoding"
],
"methods": [
"encode",
"encodeInto"
]
},
"TextEncoderCommon": {
"attributes": [
"encoding"
],
"methods": []
},
"TextEncoderStream": {
"attributes": [
"encoding",
"readable",
"writable"
],
"methods": []
},
"TextEvent": {
"attributes": [
"data"
],
"methods": [
"initTextEvent"
]
},
"TextMetrics": {
"attributes": [
"actualBoundingBoxAscent",
"actualBoundingBoxDescent",
"actualBoundingBoxLeft",
"actualBoundingBoxRight",
"alphabeticBaseline",
"emHeightAscent",
"emHeightDescent",
"fontBoundingBoxAscent",
"fontBoundingBoxDescent",
"hangingBaseline",
"ideographicBaseline",
"width"
],
"methods": []
},
"TextTrack": {
"attributes": [
"activeCues",
"cues",
"id",
"inBandMetadataTrackDispatchType",
"kind",
"label",
"language",
"mode",
"oncuechange"
],
"methods": [
"addCue",
"removeCue"
]
},
"TextTrackCue": {
"attributes": [
"endTime",
"id",
"onenter",
"onexit",
"pauseOnExit",
"startTime",
"track"
],
"methods": []
},
"TextTrackCueList": {
"attributes": [
"length"
],
"methods": [
"getCueById"
]
},
"TextTrackList": {
"attributes": [
"length",
"onaddtrack",
"onchange",
"onremovetrack"
],
"methods": [
"getTrackById"
]
},
"TimeRanges": {
"attributes": [
"length"
],
"methods": [
"end",
"start"
]
},
"ToggleEvent": {
"attributes": [
"newState",
"oldState",
"source"
],
"methods": []
},
"Touch": {
"attributes": [
"altitudeAngle",
"azimuthAngle",
"clientX",
"clientY",
"force",
"identifier",
"pageX",
"pageY",
"radiusX",
"radiusY",
"rotationAngle",
"screenX",
"screenY",
"target",
"touchType"
],
"methods": []
},
"TouchEvent": {
"attributes": [
"altKey",
"changedTouches",
"ctrlKey",
"metaKey",
"shiftKey",
"targetTouches",
"touches"
],
"methods": [
"getModifierState"
]
},
"TouchList": {
"attributes": [
"length"
],
"methods": [
"item"
]
},
"TransformStream": {
"attributes": [
"readable",
"writable"
],
"methods": []
},
"TransformStreamDefaultController": {
"attributes": [
"desiredSize"
],
"methods": [
"enqueue",
"error",
"terminate"
]
},
"TreeWalker": {
"attributes": [
"currentNode",
"filter",
"root",
"whatToShow"
],
"methods": [
"firstChild",
"lastChild",
"nextNode",
"nextSibling",
"parentNode",
"previousNode",
"previousSibling"
]
},
"UIEvent": {
"attributes": [
"detail",
"view",
"which"
],
"methods": [
"initUIEvent"
]
},
"URL": {
"attributes": [
"hash",
"host",
"hostname",
"href",
"origin",
"password",
"pathname",
"port",
"protocol",
"search",
"searchParams",
"username"
],
"methods": [
"canParse",
"createObjectURL",
"parse",
"revokeObjectURL",
"toJSON"
]
},
"URLPattern": {
"attributes": [
"hasRegExpGroups",
"hash",
"hostname",
"password",
"pathname",
"port",
"protocol",
"search",
"username"
],
"methods": [
"exec",
"test"
]
},
"URLSearchParams": {
"attributes": [
"size"
],
"methods": [
"append",
"delete",
"get",
"getAll",
"has",
"set",
"sort"
]
},
"UserActivation": {
"attributes": [
"hasBeenActive",
"isActive"
],
"methods": []
},
"ValidityState": {
"attributes": [
"badInput",
"customError",
"patternMismatch",
"rangeOverflow",
"rangeUnderflow",
"stepMismatch",
"tooLong",
"tooShort",
"typeMismatch",
"valid",
"valueMissing"
],
"methods": []
},
"VideoTrack": {
"attributes": [
"id",
"kind",
"label",
"language",
"selected"
],
"methods": []
},
"VideoTrackList": {
"attributes": [
"length",
"onaddtrack",
"onchange",
"onremovetrack",
"selectedIndex"
],
"methods": [
"getTrackById"
]
},
"VisibilityStateEntry": {
"attributes": [
"duration",
"entryType",
"name",
"startTime"
],
"methods": []
},
"VisualViewport": {
"attributes": [
"height",
"offsetLeft",
"offsetTop",
"onresize",
"onscroll",
"onscrollend",
"pageLeft",
"pageTop",
"scale",
"width"
],
"methods": []
},
"WebSocket": {
"attributes": [
"binaryType",
"bufferedAmount",
"extensions",
"onclose",
"onerror",
"onmessage",
"onopen",
"protocol",
"readyState",
"url"
],
"methods": [
"close",
"send"
]
},
"WheelEvent": {
"attributes": [
"deltaMode",
"deltaX",
"deltaY",
"deltaZ",
"momentum"
],
"methods": []
},
"Window": {
"attributes": [
"clientInformation",
"closed",
"crossOriginIsolated",
"customElements",
"devicePixelRatio",
"document",
"external",
"frameElement",
"frames",
"history",
"indexedDB",
"innerHeight",
"innerWidth",
"isSecureContext",
"length",
"localStorage",
"location",
"locationbar",
"menubar",
"name",
"navigation",
"navigator",
"onabort",
"onafterprint",
"onauxclick",
"onbeforeinput",
"onbeforematch",
"onbeforeprint",
"onbeforetoggle",
"onbeforeunload",
"onblur",
"oncancel",
"oncanplay",
"oncanplaythrough",
"onchange",
"onclick",
"onclose",
"oncommand",
"oncontextlost",
"oncontextmenu",
"oncontextrestored",
"oncopy",
"oncuechange",
"oncut",
"ondblclick",
"ondrag",
"ondragend",
"ondragenter",
"ondragleave",
"ondragover",
"ondragstart",
"ondrop",
"ondurationchange",
"onemptied",
"onended",
"onerror",
"onfocus",
"onformdata",
"ongamepadconnected",
"ongamepaddisconnected",
"ongotpointercapture",
"onhashchange",
"oninput",
"oninvalid",
"onkeydown",
"onkeypress",
"onkeyup",
"onlanguagechange",
"onload",
"onloadeddata",
"onloadedmetadata",
"onloadstart",
"onlostpointercapture",
"onmessage",
"onmessageerror",
"onmousedown",
"onmouseenter",
"onmouseleave",
"onmousemove",
"onmouseout",
"onmouseover",
"onmouseup",
"onoffline",
"ononline",
"onpagehide",
"onpagereveal",
"onpageshow",
"onpageswap",
"onpaste",
"onpause",
"onplay",
"onplaying",
"onpointercancel",
"onpointerdown",
"onpointerenter",
"onpointerleave",
"onpointermove",
"onpointerout",
"onpointerover",
"onpointerrawupdate",
"onpointerup",
"onpopstate",
"onprogress",
"onratechange",
"onrejectionhandled",
"onreset",
"onresize",
"onscroll",
"onscrollend",
"onsecuritypolicyviolation",
"onseeked",
"onseeking",
"onselect",
"onselectionchange",
"onselectstart",
"onslotchange",
"onstalled",
"onstorage",
"onsubmit",
"onsuspend",
"ontimeupdate",
"ontoggle",
"ontouchcancel",
"ontouchend",
"ontouchmove",
"ontouchstart",
"onunhandledrejection",
"onunload",
"onvolumechange",
"onwaiting",
"onwebkitanimationend",
"onwebkitanimationiteration",
"onwebkitanimationstart",
"onwebkittransitionend",
"onwheel",
"opener",
"origin",
"originAgentCluster",
"outerHeight",
"outerWidth",
"pageXOffset",
"pageYOffset",
"parent",
"performance",
"personalbar",
"screen",
"screenLeft",
"screenTop",
"screenX",
"screenY",
"scrollX",
"scrollY",
"scrollbars",
"self",
"sessionStorage",
"status",
"statusbar",
"toolbar",
"top",
"visualViewport",
"window"
],
"methods": [
"alert",
"atob",
"blur",
"btoa",
"cancelAnimationFrame",
"cancelIdleCallback",
"captureEvents",
"clearInterval",
"clearTimeout",
"close",
"confirm",
"createImageBitmap",
"fetch",
"fetchLater",
"focus",
"getComputedStyle",
"getSelection",
"matchMedia",
"moveBy",
"moveTo",
"open",
"postMessage",
"print",
"prompt",
"queueMicrotask",
"releaseEvents",
"reportError",
"requestAnimationFrame",
"requestIdleCallback",
"resizeBy",
"resizeTo",
"scroll",
"scrollBy",
"scrollTo",
"setInterval",
"setTimeout",
"stop",
"structuredClone"
]
},
"WindowEventHandlers": {
"attributes": [
"onafterprint",
"onbeforeprint",
"onbeforeunload",
"ongamepadconnected",
"ongamepaddisconnected",
"onhashchange",
"onlanguagechange",
"onmessage",
"onmessageerror",
"onoffline",
"ononline",
"onpagehide",
"onpagereveal",
"onpageshow",
"onpageswap",
"onpopstate",
"onrejectionhandled",
"onstorage",
"onunhandledrejection",
"onunload"
],
"methods": []
},
"WindowLocalStorage": {
"attributes": [
"localStorage"
],
"methods": []
},
"WindowOrWorkerGlobalScope": {
"attributes": [
"crossOriginIsolated",
"indexedDB",
"isSecureContext",
"origin",
"performance"
],
"methods": [
"atob",
"btoa",
"clearInterval",
"clearTimeout",
"createImageBitmap",
"fetch",
"queueMicrotask",
"reportError",
"setInterval",
"setTimeout",
"structuredClone"
]
},
"WindowSessionStorage": {
"attributes": [
"sessionStorage"
],
"methods": []
},
"Worker": {
"attributes": [
"onerror",
"onmessage",
"onmessageerror"
],
"methods": [
"postMessage",
"terminate"
]
},
"WorkerGlobalScope": {
"attributes": [
"crossOriginIsolated",
"fonts",
"indexedDB",
"isSecureContext",
"location",
"navigator",
"onerror",
"onlanguagechange",
"onoffline",
"ononline",
"onrejectionhandled",
"onunhandledrejection",
"origin",
"performance",
"self"
],
"methods": [
"atob",
"btoa",
"clearInterval",
"clearTimeout",
"createImageBitmap",
"fetch",
"importScripts",
"queueMicrotask",
"reportError",
"setInterval",
"setTimeout",
"structuredClone"
]
},
"WorkerNavigator": {
"attributes": [
"appCodeName",
"appName",
"appVersion",
"hardwareConcurrency",
"hash",
"host",
"hostname",
"href",
"language",
"languages",
"onLine",
"origin",
"oscpu",
"pathname",
"platform",
"port",
"product",
"productSub",
"protocol",
"search",
"storage",
"userAgent",
"vendor",
"vendorSub"
],
"methods": [
"taintEnabled"
]
},
"WorkletGlobalScope": {
"attributes": [],
"methods": [
"addModule"
]
},
"WritableStream": {
"attributes": [
"locked"
],
"methods": [
"abort",
"close",
"getWriter"
]
},
"WritableStreamDefaultController": {
"attributes": [
"signal"
],
"methods": [
"error"
]
},
"WritableStreamDefaultWriter": {
"attributes": [
"closed",
"desiredSize",
"ready"
],
"methods": [
"abort",
"close",
"releaseLock",
"write"
]
},
"XMLHttpRequest": {
"attributes": [
"onreadystatechange",
"readyState",
"response",
"responseText",
"responseType",
"responseURL",
"responseXML",
"status",
"statusText",
"timeout",
"upload",
"withCredentials"
],
"methods": [
"abort",
"getAllResponseHeaders",
"getResponseHeader",
"open",
"overrideMimeType",
"send",
"setRequestHeader"
]
},
"XMLHttpRequestEventTarget": {
"attributes": [
"onabort",
"onerror",
"onload",
"onloadend",
"onloadstart",
"onprogress",
"ontimeout"
],
"methods": []
},
"XMLSerializer": {
"attributes": [],
"methods": [
"serializeToString"
]
},
"XPathEvaluator": {
"attributes": [],
"methods": [
"createExpression",
"createNSResolver",
"evaluate"
]
},
"XPathEvaluatorBase": {
"attributes": [],
"methods": [
"createExpression",
"createNSResolver",
"evaluate"
]
},
"XPathExpression": {
"attributes": [],
"methods": [
"evaluate"
]
},
"XPathNSResolver": {
"attributes": [],
"methods": [
"lookupNamespaceURI"
]
},
"XPathResult": {
"attributes": [
"booleanValue",
"invalidIteratorState",
"numberValue",
"resultType",
"singleNodeValue",
"snapshotLength",
"stringValue"
],
"methods": [
"iterateNext",
"snapshotItem"
]
},
"XSLTProcessor": {
"attributes": [],
"methods": [
"clearParameters",
"getParameter",
"importStylesheet",
"removeParameter",
"reset",
"setParameter",
"transformToDocument",
"transformToFragment"
]
},
"console": {
"attributes": [],
"methods": [
"assert",
"clear",
"count",
"countReset",
"debug",
"dir",
"dirxml",
"error",
"group",
"groupCollapsed",
"groupEnd",
"info",
"log",
"table",
"time",
"timeEnd",
"timeLog",
"trace",
"warn"
]
}
};
