#!/usr/bin/env bash
# Build the NetSurf framebuffer frontend for the Vita as a static library and
# stage the runtime resources for packaging.
#
# Usage: ./scripts/build-netsurf.sh [clean]
#
# Output (consumed by CMakeLists.txt):
#   out/netsurf/libnetsurf.a
#   out/netsurf/resources/      Messages, CSS, internal HTML pages
#
# Set VITASURF_DEBUG=1 for a build with verbose logging compiled in, and
# VITASURF_JS_ENGINE to quickjs (default), duktape or no to pick the
# JavaScript engine; pass the same choice to CMake as -DVITASURF_JS_ENGINE.
# VITASURF_JS=NO is still accepted and means VITASURF_JS_ENGINE=no.
# Requires scripts/build-deps.sh to have run first (it also builds the
# nsgenbind host tool the Duktape bindings need).
set -euo pipefail

VITASURF_JS_ENGINE="${VITASURF_JS_ENGINE:-quickjs}"
if [ "${VITASURF_JS:-YES}" = "NO" ]; then
    VITASURF_JS_ENGINE=no
fi
case "$VITASURF_JS_ENGINE" in
    duktape|quickjs|no) ;;
    *) echo "error: VITASURF_JS_ENGINE must be duktape, quickjs or no" >&2; exit 1 ;;
esac

. "$(dirname "${BASH_SOURCE[0]}")/vita-env.sh"

NETSURF="$VITASURF_ROOT/deps/netsurf"
OUT="$VITASURF_ROOT/out/netsurf"
OBJROOT="build/$NETSURF_HOST-framebuffer"

"$VITASURF_ROOT/scripts/apply-patches.sh"

# NetSurf reads Makefile.config from its own tree. Keep the master copy in
# vita/netsurf/ so the submodule stays untouched.
cp "$VITASURF_ROOT/vita/netsurf/Makefile.config" "$NETSURF/Makefile.config"

# nsgenbind from build-deps.sh
export PATH="$VITASURF_ROOT/out/host/bin:$PATH"

MAKE_ARGS=(
    TARGET=framebuffer
    "HOST=$NETSURF_HOST"
    "CC=$TARGET_CC"
    "CXX=$TARGET_CXX"
    "AR=$TARGET_AR"
    "PKG_CONFIG=$NETSURF_PKG_CONFIG"
    "VITASURF_DEBUG=${VITASURF_DEBUG:-0}"
    "VITASURF_JS_ENGINE=$VITASURF_JS_ENGINE"
    Q=@
)

if [ "${1:-}" = "clean" ]; then
    make -C "$NETSURF" "${MAKE_ARGS[@]}" clean
    rm -rf "$OUT"
    exit 0
fi

echo "==== netsurf ($OBJROOT, JavaScript engine: $VITASURF_JS_ENGINE)"
# -k keeps compiling after an error so one run reports every broken file.
make -C "$NETSURF" "${MAKE_ARGS[@]}" -j"$JOBS" -k "$OBJROOT/libnetsurf.a"

echo "==== staging into $OUT"
rm -rf "$OUT"
mkdir -p "$OUT/resources"
cp "$NETSURF/$OBJROOT/libnetsurf.a" "$OUT/libnetsurf.a"

# Same list as install-framebuffer in frontends/framebuffer/Makefile, plus
# the English message catalogue generated by the build.
RES="$NETSURF/frontends/framebuffer/res"
for f in adblock.css credits.html default.css internal.css licence.html \
         netsurf.png quirks.css welcome.html; do
    cp "$RES/$f" "$OUT/resources/$f"
done
cp "$RES/en/Messages" "$OUT/resources/Messages"

ls -l "$OUT/libnetsurf.a"
