#!/usr/bin/env bash
# Build the NetSurf framebuffer frontend for the Vita as a static library and
# stage the runtime resources for packaging.
#
# Usage: ./scripts/build-netsurf.sh [clean]
#
# Output (consumed by CMakeLists.txt):
#   out/netsurf/libnetsurf.a
#   out/netsurf/resources/      Messages, CSS, internal HTML pages
#
# Set VITASURF_DEBUG=1 for a build with verbose logging compiled in.
# Requires scripts/build-deps.sh to have run first.
set -euo pipefail

. "$(dirname "${BASH_SOURCE[0]}")/vita-env.sh"

NETSURF="$VITASURF_ROOT/deps/netsurf"
OUT="$VITASURF_ROOT/out/netsurf"
OBJROOT="build/$NETSURF_HOST-framebuffer"

"$VITASURF_ROOT/scripts/apply-patches.sh"

# NetSurf reads Makefile.config from its own tree. Keep the master copy in
# vita/netsurf/ so the submodule stays untouched.
cp "$VITASURF_ROOT/vita/netsurf/Makefile.config" "$NETSURF/Makefile.config"

MAKE_ARGS=(
    TARGET=framebuffer
    "HOST=$NETSURF_HOST"
    "CC=$TARGET_CC"
    "CXX=$TARGET_CXX"
    "AR=$TARGET_AR"
    "PKG_CONFIG=$NETSURF_PKG_CONFIG"
    "VITASURF_DEBUG=${VITASURF_DEBUG:-0}"
    Q=@
)

if [ "${1:-}" = "clean" ]; then
    make -C "$NETSURF" "${MAKE_ARGS[@]}" clean
    rm -rf "$OUT"
    exit 0
fi

echo "==== netsurf ($OBJROOT)"
make -C "$NETSURF" "${MAKE_ARGS[@]}" -j"$JOBS" "$OBJROOT/libnetsurf.a"

echo "==== staging into $OUT"
rm -rf "$OUT"
mkdir -p "$OUT/resources"
cp "$NETSURF/$OBJROOT/libnetsurf.a" "$OUT/libnetsurf.a"

# Same list as install-framebuffer in frontends/framebuffer/Makefile, plus
# the English message catalogue generated by the build.
RES="$NETSURF/frontends/framebuffer/res"
for f in adblock.css credits.html default.css internal.css licence.html \
         netsurf.png quirks.css welcome.html; do
    cp "$RES/$f" "$OUT/resources/$f"
done
cp "$RES/en/Messages" "$OUT/resources/Messages"

ls -l "$OUT/libnetsurf.a"
