/*
 * Copyright 2026 VitaSurf contributors
 *
 * This file is part of VitaSurf, a PS Vita port of NetSurf.
 * Licensed under the GNU General Public License version 2.
 */

/*
 * Intl.NumberFormat and Intl.PluralRules (VitaSurf).
 *
 * The prelude's stand-ins knew English and little else, and a page could
 * tell: Home Assistant asks for 10000 as "1E4 bits" and for Spanish,
 * gets neither, and loads FormatJS's NumberFormat and PluralRules with
 * their locale data before it draws anything. These are ECMA-402's,
 * options read as the spec reads them, the number rounded as a decimal
 * (never through floating point) and laid out as ICU lays it out, since
 * that is what every browser runs.
 *
 * The data is CLDR's, for every locale ICU has, generated by
 * scripts/gen-intl-numbers.mjs into resources/intl.pak and read from it
 * through vita/js/intl.c one locale at a time, when a page first asks
 * for that locale; a locale's entry is what it changes from its parent.
 *
 * A number is carried as a decimal: { neg, d, q } is (-1)^neg times the
 * digits d times ten to the q, with d free of leading and trailing zeros
 * ('' for zero). NaN and the infinities are { nan } and { inf, neg }.
 *
 * Written so that it runs under Node too, to be held against ICU there
 * with the cases scripts/gen-intl-number-tests.mjs makes:
 * __vitaIntlNumber(W, N, C, install) builds the two constructors onto
 * W.Intl, reading the pack through N.pak. Without the pack the prelude's
 * stand-ins stay.
 */
var __vitaIntlNumber = function (W, N, C, install) {
	'use strict';

	var Intl = W.Intl;

	/* ---- data ---- */

	var INDEX = null, LOADED = { n: {}, c: {} }, PLURALS = null;

	function index() {
		return INDEX || (INDEX = JSON.parse(N.pak('index')));
	}

	/* what diff changes in base; neither is modified */
	function merge(base, diff) {
		var out = {}, k;

		if (diff === null || typeof diff !== 'object' ||
		    Array.isArray(diff) || base === null ||
		    typeof base !== 'object' || Array.isArray(base))
			return diff;
		for (k in base)
			out[k] = base[k];
		for (k in diff)
			out[k] = merge(base[k], diff[k]);
		return out;
	}

	/* a CLDR locale's data, kind 'n' (numbers) or 'c' (currency names),
	 * with what it inherits */
	function entry(kind, tag) {
		var cache = LOADED[kind], d, p;

		if (cache[tag])
			return cache[tag];
		d = JSON.parse(N.pak(kind + ':' + tag) || '{}');
		p = index().parents[tag];
		if (p)
			d = merge(entry(kind, p), d);
		cache[tag] = d;
		return d;
	}

	/* the CLDR locale an available locale takes its data from */
	function dataTag(tag) {
		return index().locales[tag] || tag;
	}

	function hasLocale(t) {
		return Object.prototype.hasOwnProperty.call(index().locales, t) ?
			t : null;
	}

	function defaultLocale() {
		var l = (W.navigator && W.navigator.language) || 'en-US';

		return C.lookup(l, hasLocale) || 'en-US';
	}

	/*
	 * ECMA-402 ResolveLocale for the one extension key both constructors
	 * know, nu (NumberFormat's; PluralRules passes no key). Returns the
	 * locale as resolvedOptions reports it and the numbering system.
	 */
	function resolveLocale(requested, nuOption, withNu, has) {
		var i, found = null, kw = {};

		for (i = 0; i < requested.length && !found; i++) {
			var s = C.splitTag(requested[i]);

			found = C.lookup(s.base, has || hasLocale);
			if (found)
				kw = s.kw;
		}
		if (!found)
			found = has ? (W.navigator && W.navigator.language) ||
				'en-US' : defaultLocale();
		if (!withNu)
			return { locale: found, tag: found };
		var nus = index().ns, data = entry('n', dataTag(found));
		var nu = data.nu, ext = '';

		if (kw.nu !== undefined && nus[kw.nu]) {
			nu = kw.nu;
			ext = '-u-nu-' + kw.nu;
		}
		if (nuOption !== undefined && nus[nuOption] &&
		    nuOption !== nu) {
			nu = nuOption;
			ext = '';
		}
		return { locale: found + ext, tag: found, nu: nu };
	}

	function supported(locales, options, has) {
		var req = C.localeList(locales), out = [], i;

		if (options !== undefined) {
			options = toObject(options);
			getOption(options, 'localeMatcher', ['lookup', 'best fit'],
				  'best fit');
		}
		for (i = 0; i < req.length; i++) {
			if (C.lookup(C.splitTag(req[i]).base, has || hasLocale))
				out.push(req[i]);
		}
		return out;
	}

	/* ---- options ---- */

	function toObject(o) {
		if (o === null || o === undefined)
			throw new TypeError('Cannot convert undefined or null to ' +
					    'object');
		return Object(o);
	}

	function getOption(o, name, allowed, fallback) {
		var v = o[name];

		if (v === undefined)
			return fallback;
		v = String(v);
		if (allowed && allowed.indexOf(v) < 0)
			throw new RangeError('Value ' + v + ' out of range for ' +
					     'Intl options property ' + name);
		return v;
	}

	function defaultNumber(v, min, max, fallback, name) {
		if (v === undefined)
			return fallback;
		v = Number(v);
		if (isNaN(v) || v < min || v > max)
			throw new RangeError(name + ' value is out of range.');
		return Math.floor(v);
	}

	var INCREMENTS = [1, 2, 5, 10, 20, 25, 50, 100, 200, 250, 500, 1000,
		2000, 2500, 5000];
	var MODES = ['ceil', 'floor', 'expand', 'trunc', 'halfCeil',
		'halfFloor', 'halfExpand', 'halfTrunc', 'halfEven'];

	/* ECMA-402 SetNumberFormatDigitOptions */
	function digitOptions(s, o, mnfdDefault, mxfdDefault, notation) {
		var mnid = defaultNumber(o.minimumIntegerDigits, 1, 21, 1,
					 'minimumIntegerDigits');
		var mnfd = o.minimumFractionDigits, mxfd = o.maximumFractionDigits;
		var mnsd = o.minimumSignificantDigits;
		var mxsd = o.maximumSignificantDigits;
		var inc = defaultNumber(o.roundingIncrement, 1, 5000, 1,
					'roundingIncrement');

		if (INCREMENTS.indexOf(inc) < 0)
			throw new RangeError('roundingIncrement value is out of ' +
					     'range.');
		var mode = getOption(o, 'roundingMode', MODES, 'halfExpand');
		var prio = getOption(o, 'roundingPriority',
				     ['auto', 'morePrecision', 'lessPrecision'],
				     'auto');
		var tzd = getOption(o, 'trailingZeroDisplay',
				    ['auto', 'stripIfInteger'], 'auto');

		if (inc !== 1)
			mxfdDefault = mnfdDefault;
		s.minimumIntegerDigits = mnid;
		s.roundingIncrement = inc;
		s.roundingMode = mode;
		s.trailingZeroDisplay = tzd;
		var hasSd = mnsd !== undefined || mxsd !== undefined;
		var hasFd = mnfd !== undefined || mxfd !== undefined;
		var needSd = true, needFd = true;

		if (prio === 'auto') {
			needSd = hasSd;
			if (needSd || (!hasFd && notation === 'compact'))
				needFd = false;
		}
		if (needSd) {
			if (hasSd) {
				s.minimumSignificantDigits = defaultNumber(mnsd, 1, 21,
					1, 'minimumSignificantDigits');
				s.maximumSignificantDigits = defaultNumber(mxsd,
					s.minimumSignificantDigits, 21, 21,
					'maximumSignificantDigits');
			} else {
				s.minimumSignificantDigits = 1;
				s.maximumSignificantDigits = 21;
			}
		}
		if (needFd) {
			if (hasFd) {
				mnfd = defaultNumber(mnfd, 0, 100, undefined,
						     'minimumFractionDigits');
				mxfd = defaultNumber(mxfd, 0, 100, undefined,
						     'maximumFractionDigits');
				if (mnfd === undefined)
					mnfd = Math.min(mnfdDefault, mxfd);
				else if (mxfd === undefined)
					mxfd = Math.max(mxfdDefault, mnfd);
				else if (mnfd > mxfd)
					throw new RangeError('maximumFractionDigits ' +
							     'value is out of range.');
				s.minimumFractionDigits = mnfd;
				s.maximumFractionDigits = mxfd;
			} else {
				s.minimumFractionDigits = mnfdDefault;
				s.maximumFractionDigits = mxfdDefault;
			}
		}
		if (!needSd && !needFd) {
			s.minimumFractionDigits = 0;
			s.maximumFractionDigits = 0;
			s.minimumSignificantDigits = 1;
			s.maximumSignificantDigits = 2;
			s.roundingType = 'morePrecision';
			s.roundingPriority = 'morePrecision';
		} else if (prio !== 'auto') {
			s.roundingType = prio;
			s.roundingPriority = prio;
		} else {
			s.roundingType = hasSd ? 'significantDigits' :
				'fractionDigits';
			s.roundingPriority = 'auto';
		}
		if (inc !== 1) {
			if (s.roundingType !== 'fractionDigits')
				throw new TypeError('roundingIncrement needs fraction ' +
						    'digits rounding');
			if (s.maximumFractionDigits !== s.minimumFractionDigits)
				throw new RangeError('maximumFractionDigits value is ' +
						     'out of range.');
		}
	}

	/* ---- the value ---- */

	var ZERO = { neg: false, d: '', q: 0 };

	/* the digits of a plain decimal or exponent form, no sign */
	function decimalOf(s, neg) {
		var m = /^(\d*)(?:\.(\d*))?(?:e([+-]?\d+))?$/i.exec(s);
		var fp = m[2] || '', d = (m[1] + fp).replace(/^0+/, '');
		var q = (m[3] ? parseInt(m[3], 10) : 0) - fp.length, t = d.length;

		while (t > 0 && d.charCodeAt(t - 1) === 48)
			t--;
		q += d.length - t;
		d = d.slice(0, t);
		return { neg: neg, d: d, q: d ? q : 0 };
	}

	function fromNumber(x) {
		var a, d, t;

		if (x !== x)
			return { nan: true };
		if (x === Infinity || x === -Infinity)
			return { inf: true, neg: x < 0 };
		if (x === 0)
			return { neg: 1 / x < 0, d: '', q: 0 };
		a = x < 0 ? -x : x;
		if (a < 1e21 && a === Math.floor(a)) {
			d = String(a);
			t = d.length;
			while (d.charCodeAt(t - 1) === 48)
				t--;
			return { neg: x < 0, d: d.slice(0, t), q: d.length - t };
		}
		/* the shortest digits that are this double, as ICU and V8
		 * format it: 1.005 is 1.005, not 1.00499999999999989... */
		return decimalOf(String(Math.abs(x)), x < 0);
	}

	/* ECMA-402 StringIntlMathematicalValue: a decimal string is taken
	 * exactly, except that past a double's range it is an infinity or
	 * a zero */
	function fromString(s) {
		var m, n;

		s = s.trim();
		if (s === '')
			return { neg: false, d: '', q: 0 };
		m = /^([+-]?)(Infinity|(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)$/
			.exec(s);
		if (m) {
			var neg = m[1] === '-';

			n = Number(m[2]);
			if (n === Infinity)
				return { inf: true, neg: neg };
			if (n === 0)
				return { neg: neg, d: '', q: 0 };
			return decimalOf(m[2], neg);
		}
		if (/^0[xX][\da-fA-F]+$|^0[oO][0-7]+$|^0[bB][01]+$/.test(s)) {
			if (Number(s) === Infinity)
				return { inf: true, neg: false };
			return decimalOf(String(BigInt(s)), false);
		}
		return { nan: true };
	}

	function toPrimitive(v) {
		var ex, r, i, f, order = ['valueOf', 'toString'];

		if (v === null || (typeof v !== 'object' &&
				   typeof v !== 'function'))
			return v;
		ex = v[Symbol.toPrimitive];
		if (ex !== undefined && ex !== null) {
			if (typeof ex !== 'function')
				throw new TypeError('Symbol.toPrimitive is not a ' +
						    'function');
			r = ex.call(v, 'number');
			if (r !== null && (typeof r === 'object' ||
					   typeof r === 'function'))
				throw new TypeError('Cannot convert object to ' +
						    'primitive value');
			return r;
		}
		for (i = 0; i < 2; i++) {
			f = v[order[i]];
			if (typeof f === 'function') {
				r = f.call(v);
				if (r === null || (typeof r !== 'object' &&
						   typeof r !== 'function'))
					return r;
			}
		}
		throw new TypeError('Cannot convert object to primitive value');
	}

	/* ECMA-402 ToIntlMathematicalValue */
	function mathValue(v) {
		var p = toPrimitive(v);

		if (typeof p === 'bigint')
			return p < 0 ? decimalOf(String(-p), true) :
				decimalOf(String(p), false);
		if (typeof p === 'string')
			return fromString(p);
		return fromNumber(Number(p));
	}

	/* ---- rounding ---- */

	/* ECMA-402 GetUnsignedRoundingMode */
	function unsignedMode(mode, neg) {
		switch (mode) {
		case 'ceil': return neg ? 'zero' : 'infinity';
		case 'floor': return neg ? 'infinity' : 'zero';
		case 'expand': return 'infinity';
		case 'trunc': return 'zero';
		case 'halfCeil': return neg ? 'half-zero' : 'half-infinity';
		case 'halfFloor': return neg ? 'half-infinity' : 'half-zero';
		case 'halfExpand': return 'half-infinity';
		case 'halfTrunc': return 'half-zero';
		}
		return 'half-even';
	}

	function roundUp(um, cmp, odd) {
		switch (um) {
		case 'zero': return false;
		case 'infinity': return true;
		case 'half-zero': return cmp > 0;
		case 'half-infinity': return cmp >= 0;
		}
		return cmp > 0 || (cmp === 0 && odd);
	}

	function trimmed(d, q) {
		var t = d.length;

		while (t > 0 && d.charCodeAt(t - 1) === 48)
			t--;
		q += d.length - t;
		d = d.slice(0, t).replace(/^0+/, '');
		return { d: d, q: d ? q : 0 };
	}

	function addOne(s) {
		var i = s.length - 1;

		while (i >= 0 && s.charAt(i) === '9')
			i--;
		if (i < 0)
			return '1' + s.replace(/9/g, '0');
		return s.slice(0, i) + String.fromCharCode(s.charCodeAt(i) + 1) +
			s.slice(i + 1).replace(/9/g, '0');
	}

	/* x (no sign) rounded to a multiple of inc times ten to the r */
	function roundAt(x, r, inc, um) {
		var keep, kept, cmp, first;

		if (!x.d)
			return { d: '', q: 0 };
		if (inc === 1) {
			if (x.q >= r)
				return { d: x.d, q: x.q };
			keep = x.d.length - (r - x.q);
			if (keep < 0) {
				kept = '';
				cmp = -1;
			} else {
				kept = x.d.slice(0, keep);
				first = x.d.charAt(keep);
				cmp = first > '5' ? 1 : first < '5' ? -1 :
					x.d.length > keep + 1 ? 1 : 0;
			}
			if (roundUp(um, cmp, kept !== '' &&
				    (kept.charCodeAt(kept.length - 1) & 1)))
				kept = addOne(kept);
			return trimmed(kept, r);
		}
		var m = Math.min(x.q, r), ten = BigInt(10);
		var v = BigInt(x.d) * ten ** BigInt(x.q - m);
		var step = BigInt(inc) * ten ** BigInt(r - m);
		var n = v / step, rem = v - n * step;

		if (rem !== BigInt(0)) {
			var twice = rem * BigInt(2);

			cmp = twice > step ? 1 : twice < step ? -1 : 0;
			if (roundUp(um, cmp, n % BigInt(2) === BigInt(1)))
				n += BigInt(1);
		}
		return trimmed(String(n * BigInt(inc)), r);
	}

	function magnitude(y) {
		return y.d ? y.d.length - 1 + y.q : 0;
	}

	/*
	 * ECMA-402 FormatNumericToString, less the sign: x rounded as s
	 * says, and the digits shown, as { y, int, frac }.
	 */
	function toDigits(s, x) {
		var um = unsignedMode(s.roundingMode, x.neg), y, last, rm;
		var sy, slast, srm, fy, flast, frm, e, p;

		if (s.roundingType !== 'fractionDigits') {
			p = s.maximumSignificantDigits;
			e = x.d ? magnitude(x) : 0;
			sy = roundAt(x, e - p + 1, 1, um);
			e = magnitude(sy);
			srm = e - p + 1;
			slast = Math.min(sy.q, e - s.minimumSignificantDigits + 1);
		}
		if (s.roundingType !== 'significantDigits') {
			frm = -s.maximumFractionDigits;
			fy = roundAt(x, frm, s.roundingIncrement, um);
			flast = Math.min(fy.q, -s.minimumFractionDigits);
		}
		switch (s.roundingType) {
		case 'significantDigits':
			y = sy;
			last = slast;
			break;
		case 'fractionDigits':
			y = fy;
			last = flast;
			break;
		case 'morePrecision':
			if (srm <= frm) {
				y = sy;
				last = slast;
			} else {
				y = fy;
				last = flast;
			}
			break;
		default:
			if (srm <= frm) {
				y = fy;
				last = flast;
			} else {
				y = sy;
				last = slast;
			}
		}
		var int, frac, nf;

		if (y.q >= 0) {
			int = y.d ? y.d + '0'.repeat(y.q) : '0';
			frac = '';
		} else {
			nf = -y.q;
			if (y.d.length > nf) {
				int = y.d.slice(0, y.d.length - nf);
				frac = y.d.slice(y.d.length - nf);
			} else {
				int = '0';
				frac = '0'.repeat(nf - y.d.length) + y.d;
			}
		}
		if (s.trailingZeroDisplay === 'stripIfInteger' && y.q >= 0)
			last = 0;
		if (last < 0 && frac.length < -last)
			frac += '0'.repeat(-last - frac.length);
		if (int.length < s.minimumIntegerDigits)
			int = '0'.repeat(s.minimumIntegerDigits - int.length) + int;
		return { y: y, int: int, frac: frac };
	}

	/* ---- plural rules ---- */

	function plurals() {
		return PLURALS || (PLURALS = JSON.parse(N.pak('plurals')));
	}

	function compileRule(src) {
		if (!src)
			return [];
		return src.split(/\s+or\s+/).map(function (and) {
			return and.split(/\s+and\s+/).map(function (rel) {
				var m = /^([niftvwec])\s*(?:%\s*(\d+))?\s*(!?=)\s*(.+)$/
					.exec(rel.trim());

				return {
					op: m[1], mod: m[2] ? +m[2] : 0,
					not: m[3] === '!=',
					ranges: m[4].split(',').map(function (r) {
						var x = r.split('..');

						return [+x[0], +(x.length > 1 ? x[1] : x[0])];
					})
				};
			});
		});
	}

	/* the rules for a locale, as [[category, rule]...] with other last,
	 * in ICU's order, which is its resource's: by name. CLDR means the
	 * rules not to overlap, and they do only where ICU's 18-digit
	 * integer operand has lost the leading digits; order decides then. */
	var RULES = {};
	var ORDER = ['few', 'many', 'one', 'two', 'zero', 'other'];
	var SPEC_ORDER = ['zero', 'one', 'two', 'few', 'many', 'other'];

	/* the languages with plural rules, which are what Intl.PluralRules
	 * has; a locale takes its language's, as in ICU, by dropping
	 * subtags (pt-AO has pt's rules, not pt-PT's) */
	function hasPlural(t) {
		var all = plurals();

		return t !== 'und' && Object.prototype.hasOwnProperty.call(all, t) ?
			t : null;
	}

	function rulesFor(tag, type) {
		var key = tag + ' ' + type, src, r, k, out;

		if (RULES[key])
			return RULES[key];
		src = C.lookup(C.splitTag(tag).base, hasPlural);
		src = src ? plurals()[src] : null;
		r = src && src[type] ? src[type] : { other: '' };
		out = [];
		for (k = 0; k < ORDER.length; k++) {
			if (r[ORDER[k]] !== undefined)
				out.push([ORDER[k], compileRule(r[ORDER[k]])]);
		}
		if (r.other === undefined)
			out.push(['other', []]);
		out.ranges = src && src.r ? src.r : null;
		RULES[key] = out;
		return out;
	}

	/* the operands of the shown digits, ten to the c of them */
	function operands(int, frac, c) {
		if (c) {
			var all = int + frac, point = int.length + c;

			if (point >= all.length) {
				int = all + '0'.repeat(point - all.length);
				frac = '';
			} else {
				int = all.slice(0, point);
				frac = all.slice(point);
			}
		}
		int = int.replace(/^0+(?=\d)/, '');
		var t = frac.replace(/0+$/, '');

		/* ICU keeps the integer operand in 64 bits: past 18 digits
		 * it is the last 18 */
		return {
			int: int, frac: frac,
			n: Number(int + (frac ? '.' + frac : '')),
			i: Number(int.length > 18 ? int.slice(-18) : int),
			v: frac.length, w: t.length,
			f: frac ? Number(frac) : 0, t: t ? Number(t) : 0,
			c: c, e: c
		};
	}

	/* ICU holds the operands as doubles, and takes a remainder of
	 * one as a double does */
	function operandMod(o, op, mod) {
		return mod ? o[op] % mod : o[op];
	}

	function matches(rule, o) {
		var i, j, k, rel, v, hit;

		if (!rule.length)
			return true;
		for (i = 0; i < rule.length; i++) {
			for (j = 0; j < rule[i].length; j++) {
				rel = rule[i][j];
				v = operandMod(o, rel.op, rel.mod);
				hit = false;
				for (k = 0; k < rel.ranges.length && !hit; k++) {
					hit = v >= rel.ranges[k][0] &&
						v <= rel.ranges[k][1] &&
						v === Math.floor(v);
				}
				if (hit === rel.not)
					break;
			}
			if (j === rule[i].length)
				return true;
		}
		return false;
	}

	function category(rules, o) {
		var i;

		for (i = 0; i < rules.length; i++) {
			if (matches(rules[i][1], o))
				return rules[i][0];
		}
		return 'other';
	}

	function rangeCategory(rules, a, b) {
		if (!rules.ranges)
			return 'other';
		return rules.ranges[a + ' ' + b] || 'other';
	}

	/* ---- patterns ---- */

	var PATTERNS = {};

	/* tokens: strings are literal text; one-letter codes are -, +, %,
	 * ‰, ~ and ¤ */
	function affix(src) {
		var out = [], lit = '', i, c;

		function flush() {
			if (lit)
				out.push({ lit: lit });
			lit = '';
		}
		for (i = 0; i < src.length; i++) {
			c = src.charAt(i);
			if (c === '\'') {
				var end = src.indexOf('\'', i + 1);

				if (end === i + 1)
					lit += '\'';
				else
					lit += src.slice(i + 1, end < 0 ? src.length : end);
				i = end < 0 ? src.length : end;
			} else if (c === '-' || c === '+' || c === '%' ||
				   c === '\u2030' || c === '~') {
				flush();
				out.push(c);
			} else if (c === '\u00a4') {
				flush();
				out.push(c);
				while (src.charAt(i + 1) === '\u00a4')
					i++;
			} else {
				lit += c;
			}
		}
		flush();
		return out;
	}

	function splitPattern(p) {
		var i, inq = false, start = -1, end = -1, c;

		for (i = 0; i < p.length; i++) {
			c = p.charAt(i);
			if (c === '\'') {
				inq = !inq;
			} else if (!inq && /[#0-9@,.]/.test(c)) {
				if (start < 0)
					start = i;
				end = i + 1;
			} else if (!inq && c === 'E' && start >= 0 && end === i) {
				end = i + 1;
				while (/[+0-9]/.test(p.charAt(end)))
					end++;
				i = end - 1;
			} else if (start >= 0 && end === i) {
				break;
			}
		}
		if (start < 0)
			return { pre: affix(p), num: '', suf: [] };
		return { pre: affix(p.slice(0, start)), num: p.slice(start, end),
			suf: affix(p.slice(end)) };
	}

	function parsePattern(p) {
		var r = PATTERNS[p], semi = -1, i, inq = false;

		if (r)
			return r;
		for (i = 0; i < p.length; i++) {
			if (p.charAt(i) === '\'')
				inq = !inq;
			else if (!inq && p.charAt(i) === ';') {
				semi = i;
				break;
			}
		}
		var pos = splitPattern(semi < 0 ? p : p.slice(0, semi));
		var neg = semi < 0 ? null : splitPattern(p.slice(semi + 1));
		var ip = pos.num.split(/[.E]/)[0].split(','), has = function (a, t) {
			return a.pre.indexOf(t) >= 0 || a.suf.indexOf(t) >= 0;
		};

		r = {
			pos: pos, neg: neg,
			g1: ip.length > 1 ? ip[ip.length - 1].length : 0,
			g2: ip.length > 2 ? ip[ip.length - 2].length :
				ip.length > 1 ? ip[ip.length - 1].length : 0,
			posPlus: has(pos, '+'),
			negMinus: neg ? has(neg, '-') : false
		};
		PATTERNS[p] = r;
		return r;
	}

	var POS = 0, PLUS = 1, NEG = 2;

	/* ICU's PatternStringUtils::patternInfoToStringBuilder: the prefix
	 * and suffix tokens for a sign */
	function affixes(pat, sign, approx) {
		var plusForMinus = sign === PLUS && !pat.posPlus;
		var useNeg = pat.neg && (sign === NEG ||
			(pat.negMinus && (plusForMinus || approx)));
		var sub = useNeg ? pat.neg : pat.pos, signs;
		var pre = sub.pre, suf = sub.suf;

		if (!useNeg && (sign === NEG || plusForMinus || approx))
			pre = ['-'].concat(pre);
		if (approx)
			signs = plusForMinus ? ['~', '+'] : sign === NEG ?
				['~', '-'] : ['~'];
		else
			signs = plusForMinus ? ['+'] : ['-'];
		function swap(list) {
			var out = [], i;

			for (i = 0; i < list.length; i++) {
				if (list[i] === '-')
					out.push.apply(out, signs);
				else
					out.push(list[i]);
			}
			return out;
		}
		return { pre: swap(pre), suf: swap(suf) };
	}

	/* ---- formatting ---- */

	var BIDI = /^([\u200e\u200f\u061c]*)([\s\S]*?)([\u200e\u200f\u061c]*)$/;

	function push(out, type, value) {
		if (!value)
			return;
		if (type === 'literal' && out.length &&
		    out[out.length - 1].type === 'literal') {
			out[out.length - 1].value += value;
			return;
		}
		out.push({ type: type, value: value });
	}

	/* a symbol, its bidi marks literal as ICU's fields leave them */
	var SPLIT = {};

	function pushSymbol(out, type, s) {
		var m = SPLIT[s] || (SPLIT[s] = BIDI.exec(s));

		push(out, 'literal', m[1]);
		push(out, type, m[2]);
		push(out, 'literal', m[3]);
	}

	/* text around the number in a compact or unit pattern: the
	 * spaces at its edges literal, the rest of the given type */
	function pushText(out, type, s) {
		var m = /^([\s\u200e\u200f\u061c]*)([\s\S]*?)([\s\u200e\u200f\u061c]*)$/
			.exec(s);

		push(out, 'literal', m[1]);
		push(out, type, m[2]);
		push(out, 'literal', m[3]);
	}

	/* a numbering system's symbols and patterns, what it lacks taken
	 * from the locale's Latin ones, as ICU does */
	var SYSTEMS = new WeakMap();

	function forSystem(d, k, nu) {
		var c = SYSTEMS.get(d), key = k + nu;

		if (!c)
			SYSTEMS.set(d, c = {});
		if (!c[key])
			c[key] = nu === 'latn' || !d[k][nu] ? d[k].latn :
				merge(d[k].latn, d[k][nu]);
		return c[key];
	}

	function symbols(s) {
		return forSystem(s.data, 'S', s.nu);
	}

	function patternsOf(s) {
		return forSystem(s.data, 'P', s.nu);
	}

	function translit(s, digits) {
		if (!digits)
			return s;
		return s.replace(/[0-9]/g, function (c) {
			return digits[c.charCodeAt(0) - 48];
		});
	}

	function currencyText(s) {
		var c = s.data.C[s.currency];

		if (s.currencyDisplay === 'code')
			return s.currency;
		if (!c || !c[0])
			return s.currency;
		if (s.currencyDisplay === 'narrowSymbol')
			return c[1] || c[0];
		return c[0];
	}

	function currencyName(s, plural) {
		var names = entry('c', dataTag(s.tag)), v = names[s.currency];
		var i;

		if (v === undefined)
			return s.currency;
		if (typeof v === 'string')
			return v;
		i = ['zero', 'one', 'two', 'few', 'many', 'other'].indexOf(plural);
		var pick = v[i + 1];

		if (pick === undefined || pick === 0)
			pick = v[6];
		if (pick === undefined || pick === 0 || pick === 1)
			pick = v[0];
		return pick;
	}

	/* the format of the currency of the region the locale names, if
	 * it has one of its own */
	function regionFormat(s) {
		if (s.regionFormat === undefined) {
			var p = C.splitTag(s.tag).base.split('-'), i, cur, v;

			s.regionFormat = null;
			for (i = 1; i < p.length; i++) {
				if (/^([A-Z]{2}|\d{3})$/.test(p[i]))
					cur = index().rc[p[i]];
			}
			v = cur && s.data.C[cur];
			if (v && v[2])
				s.regionFormat = v.slice(2);
		}
		return s.regionFormat;
	}

	/* the unit's pattern, "{0} km", for a plural category */
	function unitPattern(s, plural) {
		var u = s.data.U[s.unitDisplay], e = u[s.unit], m;

		function form(x) {
			return x[plural] || x.other;
		}
		if (e)
			return form(e);
		m = /^(.*)-per-(.*)$/.exec(s.unit);
		var num = form(u[m[1]]), den = u[m[2]];

		if (den.per)
			return den.per.replace('{0}', num);
		return u.per.replace('{1}', (den.one || den.other)
				     .replace('{0}', '').trim())
			.replace('{0}', num);
	}

	/* the compact pattern for the decimal of magnitude mag */
	function compactTable(s) {
		var p = patternsOf(s);

		if (s.style === 'currency' && s.currencyDisplay !== 'name')
			return p.cs || p.ds;
		return s.compactDisplay === 'long' && p.dl ? p.dl : p.ds;
	}

	/* a pattern of a magnitude, of any plural: they all have the same
	 * zeros */
	function anyForm(e) {
		var k;

		if (e.other)
			return e.other;
		for (k in e)
			return e[k];
		return '0';
	}

	function compactKey(table, mag) {
		var best = null, k;

		for (k in table) {
			if (k.length - 1 <= mag && (!best || k.length > best.length))
				best = k;
		}
		return best;
	}

	function exponentFor(s, mag) {
		if (s.notation === 'scientific')
			return mag;
		if (s.notation === 'engineering')
			return Math.floor(mag / 3) * 3;
		if (s.notation !== 'compact')
			return 0;
		var table = compactTable(s), key = table && compactKey(table, mag);

		if (!key)
			return 0;
		var p = anyForm(table[key]), zeros = (p.match(/0+/) || [''])[0].length;

		if (p === '0' || !zeros)
			return 0;
		return key.length - 1 - (zeros - 1);
	}

	/* ECMA-402 ComputeExponent; returns the exponent and the digits */
	function computeExponent(s, x) {
		var mag, exp, r, newMag;

		if (!x.d) {
			return { exp: 0, r: toDigits(s, x) };
		}
		mag = magnitude(x);
		exp = exponentFor(s, mag);
		r = toDigits(s, { neg: x.neg, d: x.d, q: x.q - exp });
		if (!r.y.d)
			return { exp: exp, r: r };
		newMag = magnitude(r.y);
		if (newMag === mag - exp)
			return { exp: exp, r: r };
		exp = exponentFor(s, mag + 1);
		return { exp: exp,
			r: toDigits(s, { neg: x.neg, d: x.d, q: x.q - exp }) };
	}

	function signOf(s, v, isZero) {
		switch (s.signDisplay) {
		case 'never':
			return POS;
		case 'always':
			return v.neg && !v.nan ? NEG : PLUS;
		case 'exceptZero':
			return v.nan || isZero ? POS : v.neg ? NEG : PLUS;
		case 'negative':
			return v.neg && !isZero && !v.nan ? NEG : POS;
		}
		return v.neg && !v.nan ? NEG : POS;
	}

	function groupSizes(s, pat) {
		var min;

		if (!pat.g1 || s.useGrouping === false)
			return null;
		min = s.useGrouping === 'always' ? 1 : s.useGrouping === 'min2' ?
			2 : s.data.mgd || 1;
		return { g1: pat.g1, g2: pat.g2, min: min };
	}

	/* a pattern's prefix and suffix as parts, for a sign; a formatter
	 * keeps them, since they are the same every time */
	function affixParts(s, pat, sign, approx, compact) {
		var aff = affixes(parsePattern(pat), sign, approx), sym = s.sym;
		var cur = s.style === 'currency' ? s.cur : null;

		function tokens(list) {
			var res = [], t, k;

			for (k = 0; k < list.length; k++) {
				t = list[k];
				if (typeof t === 'object')
					pushText(res, compact ? 'compact' : 'literal', t.lit);
				else if (t === '-')
					pushSymbol(res, 'minusSign', sym.minusSign);
				else if (t === '+')
					pushSymbol(res, 'plusSign', sym.plusSign);
				else if (t === '~')
					pushSymbol(res, 'approximatelySign',
						   sym.approximatelySign);
				else if (t === '%')
					pushSymbol(res, s.style === 'unit' ? 'unit' :
						   'percentSign', sym.percentSign);
				else if (t === '\u2030')
					pushSymbol(res, 'percentSign', sym.perMille);
				else if (t === '\u00a4' && cur !== null)
					pushSymbol(res, 'currency', cur);
			}
			return res;
		}
		return {
			pre: tokens(aff.pre), suf: tokens(aff.suf),
			curLast: aff.pre.length > 0 &&
				aff.pre[aff.pre.length - 1] === '\u00a4',
			curFirst: aff.suf.length > 0 && aff.suf[0] === '\u00a4'
		};
	}

	/* what a formatter works out once: its symbols and patterns, the
	 * digits of its numbering system, its currency's separators */
	var SHAPES = {};

	function prepare(s) {
		var key = [s.tag, s.nu, s.style, s.currency, s.currencyDisplay,
			s.unit, s.unitDisplay].join('\u0001');
		var shape = SHAPES[key], k;

		if (!shape) {
			shape = {};
			prepareShape(shape, s);
			SHAPES[key] = shape;
		}
		for (k in shape)
			s[k] = shape[k];
	}

	/* the same for every formatter of a locale, style and currency or
	 * unit; formatters share it */
	function prepareShape(s, from) {
		var sym, own, spec, digits = index().ns[from.nu];

		s.data = from.data;
		s.nu = from.nu;
		s.tag = from.tag;
		s.style = from.style;
		s.currency = from.currency;
		s.currencyDisplay = from.currencyDisplay;
		s.unit = from.unit;
		s.unitDisplay = from.unitDisplay;
		sym = symbols(s);
		s.sym = sym;
		s.pats = patternsOf(s);
		s.digits = s.nu !== 'latn' && digits ? Array.from(digits) : null;
		s.affixes = {};
		s.outers = {};
		s.money = { decimal: sym.decimal, group: sym.group };
		s.spec = null;
		if (s.style !== 'currency')
			return;
		/* a currency has separators of its own in some locales (de-AT
		 * groups it with a point), and a few currencies their own
		 * pattern and separators (the Cape Verdean escudo's decimal
		 * point is its sign); and as ICU does, the pattern of the
		 * locale's own currency, if it has one, is every currency's:
		 * en-BE writes dollars as it writes euros, "US$1,234.50" */
		own = s.data.C[s.currency];
		spec = own && own[2] ? own.slice(2) : regionFormat(s);
		s.spec = spec;
		s.money.decimal = spec ? spec[1] : sym.currencyDecimal ||
			sym.decimal;
		s.money.group = spec ? spec[2] : sym.currencyGroup || sym.group;
		s.cur = s.currencyDisplay !== 'name' || spec ? currencyText(s) :
			null;
	}

	/*
	 * One number's pieces, which formatToParts strings together and
	 * formatRange collapses: the number itself, the pattern's prefix and
	 * suffix (the sign, the currency, the percent sign, the compact
	 * suffix), and the unit or currency name around both.
	 */
	function pieces(s, v, approx) {
		if (!s.sym)
			prepare(s);
		var sym = s.sym, pats = s.pats, digits = s.digits, out = { value: v };
		var money = s.money, spec = s.spec;
		var r = null, exp = 0, isZero = false, pat, plural = 'other';
		var num = [], i;

		if (v.nan) {
			pushSymbol(num, 'nan', sym.nan);
		} else if (v.inf) {
			pushSymbol(num, 'infinity', sym.infinity);
		} else {
			var x = { neg: v.neg, d: v.d, q: v.q };

			if (s.style === 'percent')
				x.q += 2;
			if (s.notation === 'standard') {
				r = toDigits(s, x);
			} else {
				var ce = computeExponent(s, x);

				exp = ce.exp;
				r = ce.r;
			}
			isZero = !r.y.d;
			out.rounded = { neg: v.neg, d: r.y.d, q: r.y.q, exp: exp };
		}
		out.sign = signOf(s, v, isZero);

		/* the pattern: compact, else the style's */
		var compact = null;

		if (r && s.notation === 'compact') {
			var table = compactTable(s);
			var key = table && compactKey(table,
						      magnitude(r.y) + exp);
			/* the compact pattern goes by the plural of the number
			 * as written, 1 in "1 тысяча"; the unit or currency name
			 * by the whole number's */
			var cp = category(rulesFor(s.tag, 'c'),
					  operands(r.int, r.frac, 0));

			if (key) {
				compact = table[key][cp] || table[key].other || null;
				if (compact === '0')
					compact = null;
			}
		}
		/* the unit or currency name: compact notation's goes by the
		 * whole number rounded as the shown one is, 1235 for 1.2K */
		if (r && hasOuter(s)) {
			if (s.notation === 'compact') {
				var whole = toDigits(s, x);

				plural = category(rulesFor(s.tag, 'c'),
						  operands(whole.int, whole.frac, 0));
			} else {
				plural = category(rulesFor(s.tag, 'c'),
						  operands(r.int, r.frac, exp));
			}
		}
		/* a currency's own format, else the style's pattern; a currency
		 * written out in full takes the decimal pattern */
		if (spec)
			pat = spec[0];
		else if (s.style === 'currency' && s.currencyDisplay === 'name')
			pat = pats.d;
		else if (s.style === 'currency')
			pat = s.currencySign === 'accounting' ? pats.a : pats.c;
		else if (percentPattern(s))
			pat = pats.p;
		else
			pat = pats.d;
		var grouping = groupSizes(s, parsePattern(pat));

		if (compact)
			pat = compact;
		var akey = pat + '\u0001' + out.sign + (approx ? '~' : '');
		var aff = s.affixes[akey];

		if (!aff)
			aff = s.affixes[akey] = affixParts(s, pat, out.sign, approx,
							   !!compact);

		/* the number */
		if (r) {
			var int = r.int, groups = [];

			if (grouping && int.length >= grouping.g1 + grouping.min) {
				groups.unshift(int.slice(-grouping.g1));
				int = int.slice(0, -grouping.g1);
				while (int.length > grouping.g2) {
					groups.unshift(int.slice(-grouping.g2));
					int = int.slice(0, -grouping.g2);
				}
			}
			groups.unshift(int);
			for (i = 0; i < groups.length; i++) {
				if (i)
					pushSymbol(num, 'group', money.group);
				push(num, 'integer', translit(groups[i], digits));
			}
			if (r.frac) {
				pushSymbol(num, 'decimal', money.decimal);
				push(num, 'fraction', translit(r.frac, digits));
			}
			if (s.notation === 'scientific' ||
			    s.notation === 'engineering') {
				pushSymbol(num, 'exponentSeparator', sym.exponential);
				if (exp < 0)
					pushSymbol(num, 'exponentMinusSign',
						   sym.minusSign);
				push(num, 'exponentInteger',
				     translit(String(Math.abs(exp)), digits));
			}
		}
		out.num = num;
		out.plural = plural;
		out.exp = exp;

		/* the prefix and suffix */
		var cur = s.style === 'currency' ? s.cur : null;

		out.pre = aff.pre;
		out.suf = aff.suf;

		/* currency spacing: a currency that ends in a letter, beside a
		 * digit, is kept apart from it. Kept aside, since a range
		 * compares its affixes without it. */
		out.spBefore = out.spAfter = '';
		if (cur !== null && r) {
			var sp = pats.sp || [];

			if (aff.curLast && sp[0] && !/[\p{S}\p{Z}]$/u.test(cur))
				out.spBefore = sp[0];
			if (aff.curFirst && sp[1] && !/^[\p{S}\p{Z}]/u.test(cur))
				out.spAfter = sp[1];
		}

		/* the unit or currency name around it all */
		out.outer = outerPattern(s, plural);
		return out;
	}

	/*
	 * ICU takes a percent's pattern for a percent, and for the percent
	 * unit when it is not written out in full, except with compact
	 * notation, whose pattern takes the place of the percent's; then
	 * the percent is the unit's.
	 */
	function percentPattern(s) {
		if (s.notation === 'compact')
			return false;
		return s.style === 'percent' || (s.style === 'unit' &&
			s.unit === 'percent' && s.unitDisplay !== 'long');
	}

	function hasOuter(s) {
		if (s.style === 'currency')
			return s.currencyDisplay === 'name';
		return (s.style === 'unit' || s.style === 'percent') &&
			!percentPattern(s);
	}

	/* the unit or currency name pattern around the number, or null */
	function outerPattern(s, plural) {
		var pats = patternsOf(s);

		if (s.style === 'currency' && s.currencyDisplay === 'name')
			return (pats.cu[plural] || pats.cu.other)
				.replace('{1}', '\u0000');
		if (percentPattern(s))
			return null;
		if (s.style === 'unit')
			return unitPattern(s, plural);
		if (s.style === 'percent') {
			var e = s.data.U.short.percent;

			return e[plural] || e.other;
		}
		return null;
	}

	/* wrap parts in an outer pattern, "{0} km"; one with no {0} in
	 * it, Arabic's "ساعة" for one hour, is written without the number */
	function wrapOuter(s, outer, inner, plural) {
		var key = outer + '\u0001' + plural, o = s.outers[key], res = [];

		if (!o) {
			var at = outer.indexOf('{0}');
			var type = s.style === 'currency' ? 'currency' : 'unit';
			var text = function (t) {
				var k = t.indexOf('\u0000'), list = [];

				if (k >= 0) {
					pushText(list, 'literal', t.slice(0, k));
					push(list, 'currency', currencyName(s, plural));
					pushText(list, 'literal', t.slice(k + 1));
				} else {
					pushText(list, type, t);
				}
				return list;
			};

			o = s.outers[key] = {
				before: text(at < 0 ? outer : outer.slice(0, at)),
				after: text(at < 0 ? '' : outer.slice(at + 3)),
				number: at >= 0
			};
		}
		o.before.concat(o.number ? inner : [], o.after).forEach(
			function (p) {
				if (p.type === '\u0000')
					res.push(p);
				else
					push(res, p.type, p.value);
			});
		return res;
	}

	function lit(value) {
		return value ? [{ type: 'literal', value: value }] : [];
	}

	function partsOf(s, v, approx) {
		var p = pieces(s, v, approx), res = [];

		p.pre.concat(lit(p.spBefore), p.num, lit(p.spAfter), p.suf)
			.forEach(function (x) {
				push(res, x.type, x.value);
			});
		if (p.outer) {
			res = wrapOuter(s, p.outer, res, p.plural);
		}
		return res;
	}

	/* format's string, without making the parts */
	function stringOf(s, v) {
		var p = pieces(s, v, false), str = '', i, o;

		for (i = 0; i < p.pre.length; i++)
			str += p.pre[i].value;
		str += p.spBefore;
		for (i = 0; i < p.num.length; i++)
			str += p.num[i].value;
		str += p.spAfter;
		for (i = 0; i < p.suf.length; i++)
			str += p.suf[i].value;
		if (p.outer) {
			wrapOuter(s, p.outer, [], p.plural);
			o = s.outers[p.outer + '\u0001' + p.plural];
			str = joinParts(o.before) + (o.number ? str : '') +
				joinParts(o.after);
		}
		return str;
	}

	function joinParts(parts) {
		var s = '', i;

		for (i = 0; i < parts.length; i++)
			s += parts[i].value;
		return s;
	}

	/* ---- ranges ---- */

	function sameRounded(a, b) {
		if (a.value.inf || b.value.inf)
			return !!(a.value.inf && b.value.inf &&
				  a.value.neg === b.value.neg);
		return a.rounded.neg === b.rounded.neg &&
			a.rounded.d === b.rounded.d && a.rounded.q === b.rounded.q &&
			a.rounded.exp === b.rounded.exp;
	}

	function sameParts(a, b) {
		return JSON.stringify(a) === JSON.stringify(b);
	}

	function cpCount(parts) {
		return Array.from(joinParts(parts)).length;
	}

	/*
	 * ICU's NumberRangeFormatterImpl with collapse "auto" and identity
	 * fallback "approximately": two numbers that round the same are
	 * one, approximately; otherwise the unit or currency name is
	 * written once, in the plural the range takes, the pattern's
	 * affixes once if they are the same and more than one character,
	 * and the range's dash gets spaces round it when anything is
	 * written twice.
	 */
	function rangeParts(s, x, y) {
		var a = pieces(s, x, false), b = pieces(s, y, false);

		if (sameRounded(a, b)) {
			return partsOf(s, x, true).map(function (p) {
				return { type: p.type, value: p.value,
					source: 'shared' };
			});
		}
		var collapse = sameParts(a.pre, b.pre) && sameParts(a.suf, b.suf) &&
			cpCount(a.pre.concat(a.suf)) > 1;
		var repeat = (!collapse && cpCount(a.pre.concat(a.suf)) > 0) ||
			(!a.value.inf && (s.notation === 'scientific' ||
					  s.notation === 'engineering'));
		var sep = patternsOf(s).r || '{0}\u2013{1}';
		var mid = sep.slice(sep.indexOf('{0}') + 3, sep.indexOf('{1}'));
		var res = [], out = [];

		if (repeat) {
			if (!/^\s/.test(mid))
				mid = ' ' + mid;
			if (!/\s$/.test(mid))
				mid += ' ';
		}
		function add(list, source) {
			list.forEach(function (q) {
				res.push({ type: q.type, value: q.value,
					source: source });
			});
		}
		if (collapse) {
			add(a.pre.concat(lit(a.spBefore)), 'shared');
			add(a.num, 'startRange');
		} else {
			add(a.pre.concat(lit(a.spBefore), a.num, lit(a.spAfter), a.suf),
			    'startRange');
		}
		res.push({ type: 'literal', value: mid, source: 'shared' });
		if (collapse) {
			add(b.num, 'endRange');
			add(lit(b.spAfter).concat(a.suf), 'shared');
		} else {
			add(b.pre.concat(lit(b.spBefore), b.num, lit(b.spAfter), b.suf),
			    'endRange');
		}
		if (a.outer) {
			var plural = rangeCategory(rulesFor(s.tag, 'c'), a.plural,
						   b.plural);
			var inner = res, mark = { type: '\u0000', value: '\u0000' };
			var whole = wrapOuter(s, outerPattern(s, plural), [mark],
					      plural);
			var at = whole.indexOf(mark);

			res = [];
			add(at < 0 ? whole : whole.slice(0, at), 'shared');
			res = res.concat(inner);
			if (at >= 0)
				add(whole.slice(at + 1), 'shared');
		}
		/* adjacent literals are one part, as in ICU, and one that
		 * spans both sides is shared */
		res.forEach(function (q) {
			var l = out[out.length - 1];

			if (!q.value)
				return;
			if (l && l.type === 'literal' && q.type === 'literal') {
				l.value += q.value;
				if (l.source !== q.source)
					l.source = 'shared';
			} else {
				out.push(q);
			}
		});
		return out;
	}

	/* ---- Intl.NumberFormat ---- */

	var NF_SLOTS = new WeakMap();

	function nfSlots(nf, method) {
		var s = nf !== null && typeof nf === 'object' && NF_SLOTS.get(nf);

		if (!s)
			throw new TypeError('Method Intl.NumberFormat.prototype.' +
					    method + ' called on incompatible ' +
					    'receiver');
		return s;
	}

	function isWellFormedUnit(u) {
		var m = /^(.*)-per-(.*)$/.exec(u);

		if (UNITS.indexOf(u) >= 0)
			return true;
		return !!m && UNITS.indexOf(m[1]) >= 0 && UNITS.indexOf(m[2]) >= 0;
	}

	var UNITS = ('acre bit byte celsius centimeter day degree fahrenheit ' +
		'fluid-ounce foot gallon gigabit gigabyte gram hectare hour ' +
		'inch kilobit kilobyte kilogram kilometer liter megabit ' +
		'megabyte meter microsecond mile mile-scandinavian milliliter ' +
		'millimeter millisecond minute month nanosecond ounce percent ' +
		'petabyte pound second stone terabit terabyte week yard year')
		.split(' ');

	function createNumberFormat(nf, locales, options) {
		var req = C.localeList(locales), o, s = {}, nu, loc;

		o = options === undefined ? Object.create(null) : toObject(options);
		getOption(o, 'localeMatcher', ['lookup', 'best fit'], 'best fit');
		nu = getOption(o, 'numberingSystem', null, undefined);
		if (nu !== undefined &&
		    !/^[a-z\d]{3,8}(-[a-z\d]{3,8})*$/i.test(nu))
			throw new RangeError('Invalid numberingSystem : ' + nu);
		loc = resolveLocale(req, nu, true);
		s.locale = loc.locale;
		s.tag = loc.tag;
		s.nu = loc.nu;
		s.data = entry('n', dataTag(loc.tag));

		/* SetNumberFormatUnitOptions */
		var style = getOption(o, 'style',
				      ['decimal', 'percent', 'currency', 'unit'],
				      'decimal');
		var currency = getOption(o, 'currency', null, undefined);

		if (currency === undefined) {
			if (style === 'currency')
				throw new TypeError('Currency code is required with ' +
						    'currency style.');
		} else if (!/^[a-z]{3}$/i.test(currency)) {
			throw new RangeError('Invalid currency code : ' + currency);
		}
		var cd = getOption(o, 'currencyDisplay',
				   ['code', 'symbol', 'narrowSymbol', 'name'],
				   'symbol');
		var cs = getOption(o, 'currencySign', ['standard', 'accounting'],
				   'standard');
		var unit = getOption(o, 'unit', null, undefined);

		if (unit === undefined) {
			if (style === 'unit')
				throw new TypeError('Unit is required with unit ' +
						    'style.');
		} else if (!isWellFormedUnit(unit)) {
			throw new RangeError('Invalid unit argument for ' +
					     'Intl.NumberFormat() \'' + unit + '\'');
		}
		var ud = getOption(o, 'unitDisplay', ['short', 'narrow', 'long'],
				   'short');

		s.style = style;
		if (style === 'currency') {
			s.currency = currency.toUpperCase();
			s.currencyDisplay = cd;
			s.currencySign = cs;
		}
		if (style === 'unit') {
			s.unit = unit;
			s.unitDisplay = ud;
		}
		var notation = getOption(o, 'notation',
					 ['standard', 'scientific', 'engineering',
					  'compact'], 'standard');
		var mnfd = 0, mxfd = style === 'percent' ? 0 : 3;

		s.notation = notation;
		if (style === 'currency') {
			var cdig = index().digits[s.currency];

			mnfd = mxfd = cdig === undefined ? 2 : cdig;
		}
		digitOptions(s, o, mnfd, mxfd, notation);
		var compactDisplay = getOption(o, 'compactDisplay',
					       ['short', 'long'], 'short');
		var defGroup = 'auto';

		if (notation === 'compact') {
			s.compactDisplay = compactDisplay;
			defGroup = 'min2';
		}
		var g = o.useGrouping;

		if (g === undefined) {
			g = defGroup;
		} else if (g === true) {
			g = 'always';
		} else if (!g) {
			g = false;
		} else {
			g = String(g);
			if (['min2', 'auto', 'always', 'true', 'false'].indexOf(g) < 0)
				throw new RangeError('Value ' + g + ' out of range ' +
						     'for Intl.NumberFormat options ' +
						     'property useGrouping');
			if (g === 'true' || g === 'false')
				g = defGroup;
		}
		s.useGrouping = g;
		s.signDisplay = getOption(o, 'signDisplay',
					  ['auto', 'never', 'always', 'exceptZero',
					   'negative'], 'auto');
		NF_SLOTS.set(nf, s);
		return nf;
	}

	function NumberFormat() {
		var nf = new.target ? this : Object.create(NumberFormat.prototype);

		return createNumberFormat(nf, arguments[0], arguments[1]);
	}

	var nfProto = NumberFormat.prototype;

	function method(proto, name, fn) {
		Object.defineProperty(proto, name, {
			configurable: true, writable: true, value: fn
		});
	}

	method(nfProto, 'resolvedOptions', function resolvedOptions() {
		var s = nfSlots(this, 'resolvedOptions'), r = {}, i;
		var KEYS = ['locale', 'numberingSystem', 'style', 'currency',
			'currencyDisplay', 'currencySign', 'unit', 'unitDisplay',
			'minimumIntegerDigits', 'minimumFractionDigits',
			'maximumFractionDigits', 'minimumSignificantDigits',
			'maximumSignificantDigits', 'useGrouping', 'notation',
			'compactDisplay', 'signDisplay', 'roundingIncrement',
			'roundingMode', 'roundingPriority', 'trailingZeroDisplay'];

		for (i = 0; i < KEYS.length; i++) {
			var k = KEYS[i], v = k === 'numberingSystem' ? s.nu : s[k];

			if (v !== undefined)
				r[k] = v;
		}
		return r;
	});

	method(nfProto, 'formatToParts', function formatToParts(value) {
		var s = nfSlots(this, 'formatToParts');

		return partsOf(s, mathValue(value), false);
	});

	Object.defineProperty(nfProto, 'format', {
		configurable: true,
		get: function () {
			var s = nfSlots(this, 'format');

			if (!s.bound) {
				s.bound = function (value) {
					return stringOf(s, mathValue(value));
				};
				Object.defineProperty(s.bound, 'name', { value: '' });
			}
			return s.bound;
		}
	});

	function rangeArgs(s, a, b) {
		var x, y;

		if (a === undefined || b === undefined)
			throw new TypeError('start or end is undefined');
		x = mathValue(a);
		y = mathValue(b);
		if (x.nan || y.nan)
			throw new RangeError('Invalid number value: NaN');
		return rangeParts(s, x, y);
	}

	method(nfProto, 'formatRange', function formatRange(a, b) {
		return joinParts(rangeArgs(nfSlots(this, 'formatRange'), a, b));
	});

	method(nfProto, 'formatRangeToParts', function formatRangeToParts(a, b) {
		return rangeArgs(nfSlots(this, 'formatRangeToParts'), a, b);
	});

	Object.defineProperty(nfProto, Symbol.toStringTag, {
		configurable: true, value: 'Intl.NumberFormat'
	});
	method(NumberFormat, 'supportedLocalesOf',
	       function supportedLocalesOf(locales) {
		return supported(locales, arguments[1]);
	});
	Object.defineProperty(NumberFormat, 'prototype', { writable: false });

	/* ---- Intl.PluralRules ---- */

	var PR_SLOTS = new WeakMap();

	function prSlots(pr, method) {
		var s = pr !== null && typeof pr === 'object' && PR_SLOTS.get(pr);

		if (!s)
			throw new TypeError('Method Intl.PluralRules.prototype.' +
					    method + ' called on incompatible ' +
					    'receiver');
		return s;
	}

	function PluralRules() {
		var s = {}, o, loc;

		if (!new.target)
			throw new TypeError('Constructor Intl.PluralRules requires ' +
					    '\'new\'');
		var req = C.localeList(arguments[0]), options = arguments[1];

		o = options === undefined ? Object.create(null) : toObject(options);
		getOption(o, 'localeMatcher', ['lookup', 'best fit'], 'best fit');
		s.type = getOption(o, 'type', ['cardinal', 'ordinal'], 'cardinal');
		digitOptions(s, o, 0, 3, 'standard');
		loc = resolveLocale(req, undefined, false, hasPlural);
		s.locale = loc.locale;
		s.tag = loc.tag;
		s.rules = rulesFor(loc.tag, s.type === 'ordinal' ? 'o' : 'c');
		PR_SLOTS.set(this, s);
		return this;
	}

	var prProto = PluralRules.prototype;

	function selectOf(s, v) {
		if (v.nan || v.inf)
			return 'other';
		var r = toDigits(s, { neg: false, d: v.d, q: v.q });

		return category(s.rules, operands(r.int, r.frac, 0));
	}

	method(prProto, 'select', function select(n) {
		var s = prSlots(this, 'select');

		return selectOf(s, fromNumber(Number(n)));
	});

	method(prProto, 'selectRange', function selectRange(a, b) {
		var s = prSlots(this, 'selectRange'), x, y;

		if (a === undefined || b === undefined)
			throw new TypeError('start or end is undefined');
		x = Number(a);
		y = Number(b);
		if (x !== x || y !== y)
			throw new RangeError('Invalid number value: NaN');
		return rangeCategory(rulesFor(s.tag, 'c'),
				     selectOf(s, fromNumber(x)),
				     selectOf(s, fromNumber(y)));
	});

	method(prProto, 'resolvedOptions', function resolvedOptions() {
		var s = prSlots(this, 'resolvedOptions'), r = {}, i;
		var KEYS = ['locale', 'type', 'minimumIntegerDigits',
			'minimumFractionDigits', 'maximumFractionDigits',
			'minimumSignificantDigits', 'maximumSignificantDigits',
			'pluralCategories', 'roundingIncrement', 'roundingMode',
			'roundingPriority', 'trailingZeroDisplay'];

		for (i = 0; i < KEYS.length; i++) {
			var k = KEYS[i], v = s[k];

			if (k === 'pluralCategories')
				v = SPEC_ORDER.filter(function (c) {
					return s.rules.some(function (x) {
						return x[0] === c;
					});
				});
			if (v !== undefined)
				r[k] = v;
		}
		return r;
	});

	Object.defineProperty(prProto, Symbol.toStringTag, {
		configurable: true, value: 'Intl.PluralRules'
	});
	method(PluralRules, 'supportedLocalesOf',
	       function supportedLocalesOf(locales) {
		return supported(locales, arguments[1], hasPlural);
	});
	Object.defineProperty(PluralRules, 'prototype', { writable: false });

	Intl.NumberFormat = NumberFormat;
	Intl.PluralRules = PluralRules;

	var values = Intl.supportedValuesOf;

	Intl.supportedValuesOf = function supportedValuesOf(key) {
		key = String(key);
		if (key === 'currency')
			return index().currencies.slice();
		if (key === 'unit')
			return UNITS.slice().sort();
		if (key === 'numberingSystem')
			return Object.keys(index().ns).sort();
		return values ? values.call(this, key) : [];
	};

	if (!install)
		return;

	/* ---- Number's and BigInt's own ---- */

	var plain = null;

	function formatter(locales, options) {
		if (locales === undefined && options === undefined)
			return plain || (plain = new NumberFormat());
		return new NumberFormat(locales, options);
	}

	method(Number.prototype, 'toLocaleString', function toLocaleString() {
		var x = this;

		if (typeof x === 'object' && x instanceof Number)
			x = Number.prototype.valueOf.call(x);
		if (typeof x !== 'number')
			throw new TypeError('Number.prototype.toLocaleString ' +
					    'requires that \'this\' be a Number');
		return formatter(arguments[0], arguments[1]).format(x);
	});
	if (typeof BigInt !== 'undefined') {
		method(BigInt.prototype, 'toLocaleString',
		       function toLocaleString() {
			var x = BigInt.prototype.valueOf.call(this);

			return formatter(arguments[0], arguments[1]).format(x);
		});
	}
};

if (typeof window !== 'undefined' && window.__vitaIntl &&
    window.__vitaIntl.has && window.__vitaIntl.has('index') &&
    window.__vitaIntlCore && window.Intl)
	__vitaIntlNumber(window, window.__vitaIntl, window.__vitaIntlCore, true);

if (typeof module !== 'undefined')
	module.exports = __vitaIntlNumber;
